### ISSUE TITLE
Is it possible to register node manually, setup whole grid on multiple VMs?

### ISSUE THREAD

**Issue by tfajks** [zalando/zalenium#1037]
Is it possible to register node manually?, I have 4 vms to use for slelenium grid. I would like to run:

1st vm: hub + 1-4 nodes
2 vm: 1-4 nodes
3 vm: 1-4 nodes
4 vm: 1-4 nodes

Is it possible to configure with zalenium?

**Comment by diemol** [comment]
In short, yes, you could use Zalenium in the 1st one and the other ones as regular nodes after registering them manually to Zalenium. Or use docker-swarm or Kubernetes. Please check the docs.

Furthermore, this is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
