### ISSUE TITLE
Grouping of videos

### ISSUE THREAD

**Issue by cnealaccela** [zalando/zalenium#1041]
## 🚀 Feature Proposal

Ability to group and filter videos in the dashboard

## Motivation

We execute 1000s of automated tests, and only keep videos for the failed tests. When a significant number of tests fail we find the Dashboard limited when only showing a list of videos. What we would like is a hierarchy such as:
- Jenkins job name
- - Jenkins build number
- - - Test Name
And ability to filter on the videos by name
The Job name and Build number can be supplied as meta data of course, but i dont see the dashboard has the ability to group by meta data

## Example

A hierarchy such as:
- Jenkins job name
- - Jenkins build number
- - - Test Name

**Comment by diemol** [comment]
@cnealaccela what if you group tests by build name, and have the build name as the composition of the job name + build number?

**Comment by cnealaccela** [comment]
If i understand correctly to specify 1 piece of meta data:
"BuildName = <jobname> + <buildnumber>"
And then 1 level of heirarchy as BuildName ?
Yep should be good!

**Comment by diemol** [comment]
Yes, it is a capability, all documented here https://opensource.zalando.com/zalenium/

You pass the capability in the test, and then you can also filter by it through the search field. 

Feel free to join us in the Slack channel for more questions!

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by cnealaccela** [comment]
The documentation only refers to filtering the live preview by the "build" capability
Is that also true of the completed videos on the dashboard?

**Comment by diemol** [comment]
If the test has the build capabilitiy it can be filtered. Have you tried it?
