### ISSUE TITLE
Add Nomad support

### ISSUE THREAD

**Issue by goedelsoup** [zalando/zalenium#1084]
## 🚀 Feature Proposal

Add support for Hashicorp Nomad container executor in addition to k8s/swarm/docker. I am willing to make a PR and assist with future maintenance but want to ensure the feature is approved before proceeding.

## Motivation

While k8s may hold the majority of the market share for orchestration platforms, Nomad is in use in various stacks and is considered to be a robust, well-maintained alternative. There is already a Java client provided by Hashicorp, so the implementation of the container interface should be straight forward.

## Example

Just like the current k8s implementation, except using Nomad.

**Comment by diemol** [comment]
Hey @goedelsoup,

Thanks for bringing this up, I didn't know about Nomad.

The sad part is that due to the changes that Grid 4.x will have, it becomes really hard to migrate Zalenium to use it. It will be easier to write it from scratch.
Therefore, I have decided to work in the upstream docker-selenium project and port as many functionalities from Zalenium to it. If anyone wants to give us a hand, just start checking the open issues in the Selenium project.
Additionally, I will be around the Zalenium project in case anyone wants to help with it, I will contribute by reviewing and merging PRs, but won't be around to implement new functionalities.

Having said that, I don't think we will implement this unless someone has the time to upgrade to Selenium 4.x and add support for Nomad.
