### ISSUE TITLE
Add a cookie named zaleniumMessage in selenium python, but nothing display in video

### ISSUE THREAD

**Issue by luisxiaomai** [zalando/zalenium#1127]
I used python code likes ` driver.add_cookie( {'name':'zaleniumMessage', 'Test xxxx'})` to reference my tests steps in the recorded video, but nothing displayed in video. 

Any help is appreciated ?

**Comment by diemol** [comment]
Hi @luisxiaomai,

Since there is no reproduction scenario we cannot really say what the issue could be. Feel free to ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
