### ISSUE TITLE
responding to active maintainers request

### ISSUE THREAD

**Issue by NuRod** [zalando/zalenium#1141]
I express availability for testing/maintaining in what I can for upcoming Zalenium challenges 

Nuno Rodrigues
Quality Assurance Engineer
personal mail: naaralves@gmail.com
company mail: nuno.rodrigues@mercedes-benz.io

**Comment by diemol** [comment]
Thanks for reaching out @NuRod!

@elgalu can you please reach out to the OSS org in Zalando and see how it can be possible to add a maintainer to Zalenium?

**Comment by elgalu** [comment]
I don't have permissions, ping @hjacobs 

It would be better to move Zalenium away from Zalando as no-one inside Zalando will maintain it anymore.

**Comment by diemol** [comment]
Well, seems this got stuck and probably nothing will happen 😢 
@NuRod, perhaps try to reach out to the contact details shown at the bottom of https://opensource.zalando.com/.
Thanks!

**Comment by julianseeger** [comment]
I'm so sorry that this project is dying :cry: 

May I ask, what's your "personal" plan regarding browser testing @diemol ?  
Has zalando completely dropped selenium based testing or is it using the standard selenium grid?

**Comment by NuRod** [comment]
I just wanted to help. You can close this ticket if you want thank you. Don't know at this point, what is left to do.
 Thank you again.

**Comment by diemol** [comment]
We are working on Selenium 4 which comes with a new Grid, the most relevant features of Zalenium will be placed there. 

About Zalando, I am not sure. I don't work there anymore so I don't have insights into that information. Additionally, the project belongs legally to Zalando, that is why I cannot add or remove people from it. But if someone wants to fork it and maintain it, I can happily reference it in the README.

I will close this issue since there is not much more we can do about it. Thanks for being a great user community! 💌
