### ISSUE TITLE
[Feature] Integrate mitmweb

### ISSUE THREAD

**Issue by zodman** [zalando/zalenium#1146]
## 🚀 Feature Proposal

Integrate on the dashboard the history of request with mitmproxy

## Motivation

When the selenium it is running the runner can use mitmtproxy and then store to dump to  show on webmproxy.

## Example

![](https://i.imgur.com/qGTdjeM.png)

**Comment by diemol** [comment]
@zodman it does not sound crazy, nevertheless Zalenium is coming to an "end of life" status in the next months since it is being difficult to find new maintainers, the project belongs to the Zalando org and I am not part of it since a while ago, and additionally making Zalenium with Grid 4.0 would require a rewrite from scratch.

**Comment by diemol** [comment]
Closing as the issue went stale.
