### ISSUE TITLE
Question: Scaling Horizontally

### ISSUE THREAD

**Issue by tacf** [zalando/zalenium#115]
Hi,

From what i understood of Zalenium, you can only scale by increasing machine specs. Is it possible to run zalenium as a "classic" Selenium-Grid (Hub + serveral nodes on distinct machines).

Thanks in advance

EDIT: Sorry for the question in the issue section. Didn't know where to ask this :)

**Comment by diemol** [comment]
Hi @tacf,

True, right now the only way is to scale vertically. Two options to scale horizontally are docker swarm or kubernetes. We will work on the 2nd one, see #103, during the Summer. Zalando is starting to move to kubernetes and that's why we are taking that path.

We are dealing with some other issues now, but after that we'll start working on that. If you have some experience with kubernetes and you feel like helping, just let us know :)

No worries about posting questions here, you can also join our [gitter chat](https://gitter.im/zalando/zalenium) if you have more.

**Comment by tacf** [comment]
Hi, thanks for your quick answer. We are also looking at kubernets so that will be something to look for. Does Zalenium support any kind of browser limit configuration? I'm think of designing a Load Balance thinghy in order to have multiple Zalenium runing distributed and to have control on how many browsers we spawn in each node and make test runs pause till there is a new browser available. Think is doable? The problem is that we scale to fast and often we encounter test runs breaking due to Selenium grid reaching its limit.

**Comment by diemol** [comment]
Ah ok, I just saw the edit you made.

To be honest, I have not looked at what needs to be done for swarm. It should be less work than k8s but I have not checked it. 

It is a know issue that Selenium Grid has some problems when there are too many nodes. That is why we try to control that and make them register one by one, so the grid has time to process it.

There is this project, with the idea of balancing between grids, but it needs some maintenance
https://github.com/RetailMeNot/SeleniumGridScaler
(this to follow your initial idea, perhaps the concept can with with Zalenium).

If you have some swarm knowledge, I would appreciate any help there. You can also open an issue asking for Swarm support and we can both collaborate there.

If it is ok with you, I'll close this issue and we can handle the rest in a new one or in the gitter chat.
