### ISSUE TITLE
Dashboard doesn't work in Istio enabled Kubernetes

### ISSUE THREAD

**Issue by Hayyk** [zalando/zalenium#1154]
## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: 
Zalenium Image Version(s): 
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:

Using latest image of Zalenium on Kubernetes where Istio is enabled. Besides that Istio is enabled, pod sidecar proxy injection is also enabled for all pods. and in my dashboard I can't see any test, records, status and etc.
logs from hub contain a lot of this type of logs:

16:35:40.282 [OkHttp https://10.96.0.1/...] ERROR i.f.k.c.d.i.ExecWebSocketListener - Exec Failure: HTTP:400. Message:a container name must be specified for pod zalenium-40000-tnb4j, choose one of: [selenium-node istio-proxy] or one of the init containers: [istio-init]
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:228)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:195)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:35:40.283 [OkHttp https://10.96.0.1/...] ERROR d.z.e.z.c.k.KubernetesContainerClient - zalenium-40000-tnb4j Failed to execute command [bash, -c, start-video]
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:228)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:195)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

I need to disable Istio sidecar injection for zalenium's namespace to be able to use dashboard features. 
Sidecar proxy is needed to manage traffic in kubernetes and monitor it. so it would be better to have zalenium working in kubrenetes cluster where Istio is added.

**Comment by dkder3k** [comment]
Not sure if the idea to put zalenium hub in istio controlled environment is good.
Istio purpose is to maintain mesh-network and this paradigm is not fits the way zalenium works.
In my opinion it is better to create separate namespace in k8s cluster called something like "zalenium" without label "istio-injection=enabled" and deploy zalenium there.
Otherwise even with a fix for zalenium (to allow it to interact with Istio's envoy sidecar) you should apply additional configurations of Istio itself (add virtual service with proper routing rules and so on)

**Comment by Hayyk** [comment]
@dkder3k That is exactly what I did. I've deployed zalenium in separate namespace without istio sidecar injection enabled.
But Istio provides ingress and egress traffic management which is lifesaver if you need to prevent tests run from specific hosts, and even more if you need to restrict access to some external servers from zalenium nodes for security reasons.
Thus, I just wondering if this is possible to fix.

**Comment by dkder3k** [comment]
@Hayyk k8s itself provides nice [network policies mechanism](https://kubernetes.io/docs/concepts/services-networking/network-policies/) that allows you to manage ingress/egress traffic for any labeled pod. I agree that Istio policies much more flexible. But all this flexibility is needed for mesh-network and zalenium (in my humble opinion) should not be a part of it (at least unless there is something inside k8s cluster that uses zalenium).
Zalenium-Istio integration can be implemented, but I suppose that a lack of maintainers and amount of work are reasons why we won't see this soon.

**Comment by Btakuski** [comment]
I ran into this issue before when deploying Zalenium onto EKS w/ Istio, since Zalenium does not expect the istio-sidecar container in a pod it lead to the exception mentioned above. I could not find a solution to this and we reverted to deploying Zalenium with Istio disabled and used the vanilla K8s ingress instead.

**Comment by diemol** [comment]
Yeah, the comments are clear, especially that no maintainers are present for the project and that the Zalando org did not facilitate the continuation of the project outside of it.
Implementing this would require some efforts, and in short, there are no resources for this.
In short, Zalenium is not compatible with Istio (for now). 
I'll close this since there is sadly not a way to move forward.

**Comment by anwoolterton** [comment]
With later kubernetes 1.18+ you use the following in your service spec

```
    appProtocol: http
```
