### ISSUE TITLE
Not able to run 25 containers parallel 

### ISSUE THREAD

**Issue by vasdesai** [zalando/zalenium#1160]
Hello All, 

I am new to Zalenium.
Currently i am trying to run 25 testcases parallel. I am using following command for that..

sudo docker run --rm -ti -p 8085:4444 -v /var/run/docker.sock:/var/run/docker.sock  --privileged dosel/zalenium start --videoRecordingEnabled false --desiredContainers 25  --maxDockerSeleniumContainers 25 --maxTestSessions 25

25 containers up but all my 25 Testcases are not running parallelly.. Only few are running.. remaining testcases are getting failed by following error...
Session was terminated due to ORPHAN even though i kept Idle timeout to 600 sec

Kindly suggest the best approach to execute 25 test cases concurrently...

**Comment by Btakuski** [comment]
Per the Zalenium documentation: 
`--maxTestSessions` : Maximum amount of tests executed per container 

Since you have that value set to `25`, from my understanding there will be 25 tests executed in one container before that container is killed. I leave that value set to the default: `1` (1 test per container) to achieve parallel execution

**Comment by diemol** [comment]
I think the main issue is that to run 25 test cases in parallel, in a stable way, you need 1 CPU core per test, and if video recording is being used, then please add 1 CPU core more.
Therefore, for 25 test cases in parallel, 50 cores are needed for stable execution.
The usual recommendation is, start little, and continue increasing the amount of tests until you find something stable based on the resources (CPU and RAM) you have.
