### ISSUE TITLE
Any way to limit node containers memory?

### ISSUE THREAD

**Issue by Exoticalgi** [zalando/zalenium#126]
Is there any possibility to limit node containers memory?
I can use -m with docker when launching hub, but what about nodes?

Thank you.

**Comment by diemol** [comment]
Hi @Exoticalgi,

Right now we are sharing `/dev/shm:/dev/shm` when creating the containers and we are not limiting the memory. 

Basically because it is known that in docker-selenium containers you need to to give 1GB or 2GB so Chrome and Firefox don't crash due to lack of resources.

Before we were always allocating 2GB, but now we are just sharing the shm as shown above. So in theory the resources are better handled.

That is why it is not possible to limit the nodes memory, because this probably would make the browsers crash.

**Comment by diemol** [comment]
Nevertheless, if you have some ideas or suggestions on how to do it, we are open to it. I'll close this issue for now, but feel free to reopen with suggestions or even submit a PR with changes (much appreciated!).
