### ISSUE TITLE
Add alpine-based node images

### ISSUE THREAD

**Issue by Exoticalgi** [zalando/zalenium#129]
Consider adding alpine-based node images.

**Comment by diemol** [comment]
Hi @Exoticalgi,

Zalenium uses the node images from [elgalu/selenium](https://github.com/elgalu/docker-selenium), so please make the suggestion in that project.

Or perhaps you already know about some images we can use?

**Comment by elgalu** [comment]
That's correct, using alpine in this project won't save any space because we are also downloading docker-selenium, which uses Ubuntu.

I'm a bit concerned in investing time on this given this reported issues: https://github.com/SeleniumHQ/docker-selenium/pull/224#issuecomment-253719279

Also, @Exoticalgi do you know what % of disk space would be saved if switching to Alpine? I would like to have a clear value before considering using Alpine and all the problems it may bring switching to it, there are many things that will need to keep working like VNC, video recording and so on.

**Comment by diemol** [comment]
Closing as we didn't get any feedback from the original issue opener.
