### ISSUE TITLE
Restart node after run

### ISSUE THREAD

**Issue by diego-vieira** [zalando/zalenium#135]
Is it possible to restart the node after the test is done?
The reason is to always have another connection to come instead of waiting for zalenium to start a node on demand.

Thanks

**Comment by diemol** [comment]
Hi @diego-vieira,

Not right now, but we plan to do something like that to reuse containers instead of creating them for every request, this to help with #116.

One approach is to restart the container, another one is to just clean the logs before the next test starts and just leave the container running. We'll check which one could be better.

I'll leave this issue open since we want to work on this in the near future.

**Comment by pearj** [comment]
Had a bit of a crack at this today. Unfortunately, I was hampered by my own environmental issues for most of the day. 

@diemol turns out that there is more to it than just changing https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/DockerSeleniumRemoteProxy.java#L54 to be something other than 1. Because that only affects containers that were being cleaned up by timeout. The afterSession handler was specifically closing the container after videos/logs/etc have been copied over. 

It kinda worked after stopped it shutting down containers and started cleaning them instead. But after a while it hit the max nodes but stopped reusing containers. 

I'll have to debug in further detail.

**Comment by ketchoop** [comment]
It's a really good feature, because when it becomes more than 1000 it is really harmful to see how much time is spent to up containers :(

**Comment by borisivan** [comment]
I really like the idea of having 1 or 2 containers spun up and waiting. In the CI environment I have, execution time is critical (we block certain actions from occurring until this suite of tests is done). I have ~ 100 tests that each take 20-60 seconds each. We may run some groups of those tests in parallel at some point, but today they run in sequence.

Using elgalu/selenium and leaving that container running for the duration of the suite, there is around 7-8 seconds delay between trying to instantiate a new RemoteWebDriver, and getting it launched (each test does this). But when using Zalenium, there was ~ 10+ additional seconds to spin up the container (then the subsequent 7-8 seconds delay re: instantiating the new RemoteWebDriver). If the container could be ready and waiting, that would be a huge improvement.

I'm guessing it will be difficult to make everyone happy, since some environments using Zalenium probably have a much larger number of tests running in parallel, and 1 or 2 containers 'waiting' won't really suffice. But I sure would be happy if that functionality worked... if there was a (non default?) parameter "numberOfContainersWaiting", and I set that to <n>, then if Zalenium detects the number of containers waiting in standby mode ever dips below <n>, it spins up another one... I suspect we could pretty much eliminate the time it takes to spin up a container from affecting a test, (unless the test execution time was so quick that it was lower than the amount of time to spin up a new container... but I digress).

**Comment by diemol** [comment]
The idea is to implement this feature between this and next week, we have been catching up with stuff after the Summer holidays and this issue and #151 are up in priority for us.

We are still thinking about a proper logic for this one, but for now, the rough idea is to have a new parameter `--maxTestsPerNode`, which defaults to 1. This parameter will basically say the amount of tests that can be executed in a container before it shuts down.

When a new test request arrives, and if there is a free container, it will be executed there until `--maxTestsPerNode` is reached for subsequent requests. If no container is free, a new one will be created (unless the `--maxDockerSeleniumContainers` parameter is reached). I think this will be useful for the Kubernetes environments, usually the creation of Pods is slower than creating containers.

Ideally, this should remove in most of the cases the extra ~10 seconds needed to spin up a new container. And we would end up only with the 7-8 seconds delay between trying to instantiate a new RemoteWebDriver (which is basically the time the browser takes to start).

The `numberOfContainersWaiting` parameter is also a good idea, but it would require a thread to be monitoring the containers running all the time, I am not such a big friend of that part. For now, I think the idea I described above should also fulfil what that scenario needs.

Any ideas or comments are welcome!

**Comment by borisivan** [comment]
Just wanted to make sure I understood the previous comment correctly -- if maxTestsPerNode = 1, and there is 1 container "c1" available for tests.... when do you create the next container ("c2")? Does c2 get created shortly after the test starts running on c1, since there are now no 'spare' containers, and maxTestsPerNode = 1 (and there is a test running on "c1")?

And therefore, "c2" would be 'ready' when the _next_ test starts (which would also trigger the creation of "c3", etc, etc?

**Comment by pearj** [comment]
I'll push up how far I got a month or so ago, for reference at least.

**Comment by pearj** [comment]
@diemol For some reason `--maxTestsPerNode` didn't work too well in practice, but I didn't get into remote debugging to find out why not yet.

In my version instead of `--maxTestsPerNode` I called it `--maxUniqueTestSessions`

**Comment by diemol** [comment]
@borisivan, I think is kind of what you say, I will try to explain it through the whole lifecycle:

1. Let's say you start Zalenium with `--chromeContainers 2`, meaning that you will have two containers ready from the beginning. Also passing `--maxTestsPerNode 10`, which means that up to 10 tests will be executed in each container.
1. After that, you will start your test suite. For example, you have 40 tests and they will be executed in two threads. 
1. Then, 10 tests will be executed in the 1st container and other 10 tests will be executed in the 2nd container. After the 10th test, the container will shutdown.
1. When the 11th test request from the 1st thread is received by Zalenium, a new container will be started and as soon as it becomes available, it will execute another 10 tests before it shutdown. The same will happen with the 2nd thread.
1. This flow will continue until all the tests are processed.

I hope that it gets clearer now.

**Comment by diemol** [comment]
Thanks for pushing your code @pearj!
I'll check it and probably create a PR to merger it here.

**Comment by borisivan** [comment]
Thanks for the response. I don't think that helps my scenario, but I know you can't please everyone. I'm hoping to avoid waiting on container startup, and I also only run 1 test per container, since the video is important to me.

What I was hoping would be possible, was simply that if Zalenium detects that no more containers are available, start one. That way, there would always be one spare container "at the ready".

So if we have 40 tests, and because we use video, we only run 1 test per container, if we started with 2 containers, we'll need a new container for the 3rd test, _and every other test after that_.

If something as simple as this could be done, I think it would solve my problem:

Every 5 seconds: are there any available (unused) containers?
If yes, do nothing.
If no, start one container.

Then, it would be likely that the 'next' container would be started _during the time that the current test is running_, so that when the _next_ test tries to run, it doesn't wait on container startup.

To satisfy others, I can envision it being configurable (numberOfSpareContainers), but for what it's worth, if there was 1 container available, it would pretty much eliminate the wait-for-container-spinup that happens for tests 3-200 in a 200 test suite.

**Comment by diemol** [comment]
Oh, if your concern is about having one video per test, don't worry. It will still be like that. Even if 10 
tests are executed in each container, each test will have its own video. The video processing will be done between tests of course.

This feature would not make so much sense if we make a huge video for many tests.

**Comment by diemol** [comment]
@pearj, why didn't it work well for you?
I was just trying out your code (I changed some variable names, just minor changes), and it seems to work well. Really only a minor effort from my part.

**Comment by pearj** [comment]
Hi @diemol,

Yes, when I started lots of concurrent threads it stopped reusing containers. But I never got into a solid debug session to find out why.

**Comment by borisivan** [comment]
If there is a way to pull a container with these changes, I'd be happy to test it.

**Comment by diemol** [comment]
It seems to be working well, but I am testing on Kubernetes and bumped into #211, so I am fixing that one as well.

We'll release Monday or Tuesday :)

**Comment by diemol** [comment]
This improvement has been released https://github.com/zalando/zalenium/releases/tag/3.3.1s
