### ISSUE TITLE
[feature] hostAliases support in kubernetes

### ISSUE THREAD

**Issue by arykalin** [zalando/zalenium#246]
Hello, is it planned to support kubernetes hostAliases as it done for docker --add-host flag and extra_hosts in docker compose?

https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/

**Comment by diemol** [comment]
Hi @arykalin,

Yes, we should add it since the idea is that both environments support the same features.  We are a bit tight on schedule so we cannot work on this right now, but if you feel like, you can send us a PR for it.

**Comment by diemol** [comment]
This was added to the most recent release, please check the latest tag https://github.com/zalando/zalenium/releases/tag/3.6.0d

The way it works is straightforward, just add hostAliases to the pod or the deployment, as shown in the above link, and they will be added to the newly created pods. Something I noticed is that the added hostAliases must be valid in order to k8s to accept them and then Zalenium to start.

If any problem comes from this change, please create a new issue.
