### ISSUE TITLE
question: how to tell which container the test is running in?

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#259]
Hi,

The elgalu/selenium container [just added functionality](https://github.com/elgalu/docker-selenium/issues/157) for sending a notify message to the container that is running a test, so we can have a 'test failed' or other message to the linux desktop that ends up being recorded.

But from the notes, I have a question:

> Some steps to allow cross referencing video frames with failed tests are in place in 3.5.3-p6From Zalenium, after a test being marked as failed, is now possible to:docker exec some_chrome_or_firefox_container notify "TEST FAILED"

.. how do we know what the container is that our test is running in? I have 6 zalenium 'child' containers for running parallel tests.

If there is a capability I can query from the RemoteWebDriver object that has that container name (if Zalenium were to set it -- not sure if those things can be set after the RemoteWebDriver was already instantiated...,) that might do the trick. Or, if Zalenium implemented a way for me to just specify the test name (as specified in the RemoteWebDriver capability, which already works for the video functionality..), and it would figure it all out for me, that would be slick.

Bonus: if the elgalu (and subsequently, Zalenium) container allowed me to specify the starting x,y (and overall x,y width/height) properties of the notify, that would be huge. See the notes for [elgalu issue 157](https://github.com/elgalu/docker-selenium/issues/157) for details on that. :)

**Comment by diemol** [comment]
Based on https://github.com/elgalu/docker-selenium/issues/157, we implemented notifications showing the final test status. It is possible also to specify test steps and reference them in the video via cookies, e.g.
```
    Cookie cookie = new Cookie("zaleniumMessage", "This is my first step");
    webDriver.manage().addCookie(cookie);
    webDriver.get("http://www.homepage.com");
```

The notifications will look like this

![image](https://user-images.githubusercontent.com/5992658/31312229-de5083d2-abbd-11e7-9fc3-05d967349703.png)

**Comment by diemol** [comment]
This just got released, now Zalenium uses this functionality provided by docker-selenium and automatically will show a notification at the end of the test.

It is also possible to send step details and to have them shown in the video as notifications, please see the details in the release https://github.com/zalando/zalenium/releases/tag/3.6.0b

With this new feature, there is no need for the test to know where it is running, and feedback is appreciated. 

I'll close this issue since the feature is there now, please open a new one if a specific problem shows up based on this feature.
