### ISSUE TITLE
question: can zalenium support a test that controls multiple browsers?

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#272]
Hi,

Let's have a I have a single testNG test that creates two separate browsers (2 different RemoteWebDriver, etc). Is there a way to have them both exist in the same video? If I control the screen realestate such that each browser is only half-screen-width, that would be nice.

Almost every test we have is a single browser. But there are timing-related tests in which we want to do things simultaneously in the same single test, _as that's the purpose of that test_.

**Comment by diemol** [comment]
Hi @borisivan,

The idea sounds good, but right now, we don't have a way to accomplish that in the same video. A workaround for that would be to group the two RemoteWebDriver instances with the same `build` capability or with a similar name to identify them. Then as a post task put the videos side by side as show in this [link](https://unix.stackexchange.com/questions/233832/merge-two-video-clips-into-one-placing-them-next-to-each-other).

Besides that, some work would be needed to support that in the same container, since each container runs only one browser at the same time. Also have a way to route the test to the same container where the other one is running. 

Perhaps give it a try to the workaround and see how it goes.

**Comment by diemol** [comment]
I'll close this issue since it didn't get so much traction. If there are alternatives or new ideas, please feel free to reopen.
