### ISSUE TITLE
New Containers not launching consistently when no available node is in cleanup

### ISSUE THREAD

**Issue by stefankahn** [zalando/zalenium#335]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**
This is a follow on from [322](https://github.com/zalando/zalenium/issues/322).
When sending parallel tests at Zalenium, they are queuing up when the last remaining node is in cleanup.

Current behaviour:
Nodes are marked as available when they are in cleanup state.
This causes all new tests to be put in queue until cleanup is finished.
e.g: 10 new test requests can be put in queue when 1 container is running and in cleanup state.

Expected behaviour:
Nodes are marked as available only when they are ready to start a new test session, Otherwise a container should be spawn up to your --maxDockerSeleniumContainers limit.
Cleanup should be treated like a test session, or become part of the test session.

![screenshot from 2017-11-24 13-21-44](https://user-images.githubusercontent.com/9443575/33191111-75e89532-d11a-11e7-98f9-0dc02d309df9.png)

![screenshot from 2017-11-24 13-05-14](https://user-images.githubusercontent.com/9443575/33191107-56ef072e-d11a-11e7-9741-8ebd35134f1d.png)

Zalenium Image Version:  
3.7.1e

Docker Command to start Zalenium:  
```
    # Start in daemon mode
    docker-compose -f ${COMPOSE_FILE} -p zalenium up --force-recreate -d
```

Compose file:
```
# Usage:
#   docker-compose up --force-recreate
version: '2.1'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /tmp/videos:/home/seluser/videos
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 6
            --maxDockerSeleniumContainers 10
            --screenWidth 1930 --screenHeight 1080
            --timeZone "Pacific/Auckland"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --seleniumImageName "elgalu/selenium"
            --sendAnonymousUsageInfo false
            --maxTestSessions 10
            --keepOnlyFailedTests true
    environment:
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
```

**Comment by diemol** [comment]
HI @stefankahn,

If I remember correctly, you are running a "permanent" grid, right? (You don't start and stop Zalenium before and after running tests).

Before making the change to wait for nodes that were cleaning up, the version we had locally was working like you describe in the expected behaviour. This was creating containers too aggressively, and was using too much resources. A better approach was to wait a bit for the cleanup since containers usually need between 3-5 seconds for that.

I am not sure if we should change the behaviour to the one you mention as the expected one, I am sure this would work in your scenario but I don't know if this is ideal for other people. Perhaps one middle solution that can work is what you suggested by keeping `node count >= --desiredContainers` with a flag.

We will explore different options to find a better solution for the scenario you mention.

**Comment by stefankahn** [comment]
Hi @diemol Excuse the wall of text, but more context and information is better than less.

Yes we are running it as a "permanent" setup, but i have replicated this with an on demand setup.

This behaviour occurs when running tests in parallel.  The main issue is the node is in an "available" state when the test session is complete, not when the node is ready to start a new test. This causes the test runner to fire off the next test. When finding a node with test sessions available and in the cleanup state, the  is put in the queue.  This will occur for all new test's coming in.

Our current test execution scenario:
Running tests across 3 parallel threads.
 - 1 node is left up and is in cleanup. 
 - 3 new test requests are sent in.

Actual Result:
 - 3 tests are kept in queue.

Expected Result:
- 1 test is kept in queue for the 1 container available.
- 2 new containers spawned.


Current node states.
-------------------------------------------------------------------------------------------------
|    Test Session                                                         |        Cleanup           |
-------------------------------------------------------------------------------------------------
^a                                                                              ^b                               ^c
a.Test starts here.  Node Ready to run test.
b.Test completed.  Node is ready for cleanup. Node not ready to run test, but marked as such (Marked as available)
c. Node has completed the test run and is now back to state a


Suggestion:
I suggest not including cleanup as a test ready state "Available" until the cleanup is completed. Cleanup can take some time if you are retaining videos.
This coupled with setting  --maxDockerSeleniumContainers accurately for the docker host should avoid any aggressive container spawning behaviour.

-------------------------------------------------------------------------------------------------
|    Test Session                                                         |        Cleanup           |
-------------------------------------------------------------------------------------------------
^a                                                                              ^b                               ^c
a.Test starts here.  Node Ready to run test.
b.Test completed.  Node is ready for cleanup.
c. Node has completed the test run and is now back to state a. 


If you are happy to try the change, im happy to test it.

**Comment by diemol** [comment]
@stefankahn,

Thanks for the detailed overview :)

> Expected Result:
>1 test is kept in queue for the 1 container available.
2 new containers spawned.

Basically, that is exactly the same thing I'd like to achieve. We just need to figure out how to do it in a way we don't overload the hub by analysing the nodes continuously. 

I'll post here as soon as we advance on the topic, hopefully soon.

**Comment by stefankahn** [comment]
How does it perform if you dont consider cleanup a ready state, but leave everything else as is?

**Comment by diemol** [comment]
If we don't consider the cleanup state, and continuing with the example, 3 threads and having 3 containers running...

When the first test on each thread is done, the 2nd test on each thread will start and since the containers are finishing the cleanup, 3 new containers would be started based on the requests.

This might be ok for some scenarios, like a permanent running grid, but for the ones who start Zalenium before their tests and stop it afterwards, it is not ideal because more containers are started and in the end some of them are wasted (which means memory + CPU wasted). Test execution would also take longer because it is faster to wait for a container cleanup than starting a new one when others are running.

That's why I think the behaviour of 
> Expected Result:
1 test is kept in queue for the 1 container available.
2 new containers spawned.

would be ideal, since we reuse as much as possible and create only when needed.

**Comment by stefankahn** [comment]
I do agree that is the ideal solution.  Is it possible to to include cleanup in the test session?/ before the test status is sent back to the test runner?

**Comment by stefankahn** [comment]
Hi @diemol, Is there any progress on this?
Could a stop gap solution be to add a flag around including cleanup as a ready state?

This would allow it to be disabled if resources are not an issue for the user?

**Comment by diemol** [comment]
Hi @stefankahn,

I haven't work on this, not so much time, I am trying to get things ready to fix an issue in Kubernetes. But after that one we should be able to improve things to solve this one as well.

**Comment by diemol** [comment]
Coming back to this one, I think the easier way to go would be to have a flag indicating a "mode of operation". For example, here Zalenium is used as a permanent grid, so if new containers are created is ok because in any given moment a test will get to use it.

And the other "mode of operation" would be the current one, trying to reuse the existing containers as much as possible (which includes waiting for containers while they are being cleaned up).

What do you think?

**Comment by stefankahn** [comment]
Im not sure if a permanent grid should be treated differently to an on demand setup as the issue will happen either way, but a flag to include or exclude the cleanup as a ready state would allow me to configure the behaviour to suit.  I do like your suggestion, but what else would be included in the mode of operation flag?

**Comment by diemol** [comment]
Well, the cleanup is not included as a ready state. If this was true, an large amount of tests would fail because the node is doing something else while the test request is received.

The cleanup state is also considered as busy, but it won't start a new container since the cleanup state points out that a node will be ready soon.

What the flag would do is just to create a new container when all the existing ones are busy.

**Comment by stefankahn** [comment]
Im happy to try this. let me know how you get on.

**Comment by madskonradsen** [comment]
Nice! I'm also running a permanent grid, so I'm really looking forward to trying the flag!

**Comment by stefankahn** [comment]
@diemol Did you get a chance to include this with the latest release?

**Comment by diemol** [comment]
I was precisely working on that yesterday, I just pushed the commit. Should be released soon, probably  today or tomorrow.

**Comment by diemol** [comment]
Just merged to master, will release this soon.

You need to pass an `WAIT_FOR_AVAILABLE_NODES` env var to use this, e.g.:
```
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos -e WAIT_FOR_AVAILABLE_NODES=false \
    --privileged dosel/zalenium start --desiredContainers 2 --maxTestSessions 10
```

**Comment by diemol** [comment]
Just merged to master, will release this soon.

You need to pass an `WAIT_FOR_AVAILABLE_NODES` env var to use this, e.g.:
```
docker run --rm -ti --name zalenium -p 4444:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos -e WAIT_FOR_AVAILABLE_NODES=false \
    --privileged dosel/zalenium start --desiredContainers 2 --maxTestSessions 10
```

**Comment by diemol** [comment]
This was just released
https://github.com/zalando/zalenium/releases/tag/3.11.0a

Any feedback would be appreciated!

**Comment by stefankahn** [comment]
Thanks @diemol. I had a chance to look at this today. It worked well to keep the queue at a minimum.

I ran 4 threads and a max of 6 containers, The queue was kept under 3 and the wait times were under 6s.

**Comment by diemol** [comment]
Thanks for the feedback @stefankahn!
