### ISSUE TITLE
Choose VNC port

### ISSUE THREAD

**Issue by ryudice** [zalando/zalenium#38]
Hi, is there a way to customize the ports that are used by the nodes' VNC for the live preview? and how are the ports chosen?

**Comment by diemol** [comment]
Well, right now there is no option to customise the VNC ports. But I am interested to know why you ask the question, do you have something else in mind?

The ports are assigned from a range, just like the created nodes. 

For example, when we create the first node, we assign it the port 40000 (if the port is free, otherwise we try with 40001 and so on, until 49999). After this, we just sum 10000, and that is the VNC port (50000, 50001, and so on).

**Comment by ryudice** [comment]
I dont think it's a big deal to be honest, the reason I'm asking is because of security policies at work we can only use certain port ranges, and that one is not included.

**Comment by diemol** [comment]
Maybe we can add a customisation for port ranges as a feature in the future. But to be honest not in the near future since we have other few priorities, we could leave this issue open as a reminder.

Unless it is ok for you to use it like that, then we can close this issue.

**Comment by ryudice** [comment]
I'm going to close it since I dont think it's a big deal, I already sorted out the firewall permissions. Thanks for you help.
