### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by chmielas** [zalando/zalenium#407]
Is the way to enable ssl support in zalenium ? 
for ex. I want to connect using https://localhost:4444/grid/admin/live instead of http://localhost:4444/grid/admin/live
 
Regards,
Piotr

**Comment by diemol** [comment]
Hi @chmielas,

If you are using the docker version, it should be possible because inside the container we have Nginx serving the different resources. 
If you are using the Kubernetes one, perhaps you can secure the ingress to access the deployment.

In the docker version, changes are definitively needed for that, would you like to give us a hand with a PR?

**Comment by jrake-revelant** [comment]
thx @diemol we will give it a try and report back.

**Comment by diemol** [comment]
Closing, as it is consolidated in #645
If development starts, we'll reopen the issue.

**Comment by davidcollom** [comment]
I'm having an issue with this. Everything seems to work fine, in AWS with an ELB doing SSL Termination, however VNC is unable to connect.

I can see that VNC is attempting to do an SSL websocket (`wss://`) - but fails shortly after, switching to plain text port works perfectly fine on the same endpoint.
