### ISSUE TITLE
Add support to configure VNC default host

### ISSUE THREAD

**Issue by arielschiavoni** [zalando/zalenium#42]
Hi,

I have deployed `zalenium` to my server and it is reachable from some url let's say `test.mydomain.com`. The problem is that when I try to see the tests running, I go to the url
`test.mydomain.com:4444/grid/admin/live` which always show this:

![zalenium_live_preview](https://cloud.githubusercontent.com/assets/1364564/21385284/355af2dc-c76e-11e6-8ab3-e22614f885b7.png)

Would it be possible to add some configuration variable in which we can specify our domain?

So instead of trying to connect automatically to `http://127.0.0.1:5555/proxy/...` (which is not available) it will connect to `http://test.mydomain.com:5555/proxy/....`

The relevant code seems to be [here](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/tip/zalenium/servlet/live.java#L105)

Thanks.

**Comment by diemol** [comment]
Hi,

Thanks for reporting. This was working before and when we added BrowserStack we had to change the nginx configuration of the container, and then we broke it :(

We have already found a solution by adding a new rule in nginx, and we need to add a test for it..

We won't release the fix until next week or 1st week in January (since we are also adding another feature). I hope that's OK for you.

**Comment by arielschiavoni** [comment]
It is completely ok for me.

Thanks!

**Comment by diemol** [comment]
Just made a release that contains this fix. Please give it a try and let us know.

**Comment by arielschiavoni** [comment]
It works great thanks!

**Comment by diemol** [comment]
Cool! Thanks for letting us know!
