### ISSUE TITLE
Zalenium dashboard can not replay video

### ISSUE THREAD

**Issue by koala2012** [zalando/zalenium#472]
Hello,

I just run docker image on CentOs by command:
my docker version was:
client version :1.13.1
API version 1.26
Go version : go 1.7.5

server version :1.13.1
API version :1.26

docker run command:
docker run -d --name zalenium -p 4444:4444 \
-e TZ="Asia/Shanghai" \
-e SCREEN_WIDTH=1920 -e SCREEN_HEIGHT=1080 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v zalenium-videos:/home/seluser/videos \
--privileged dosel/zalenium start

I just run one test completely, from logs everything looks fine, but from dashboard I can not replay the videos. I just access the video url directly and got the nginx/1.10.3 404 not found, is there any nginx needed?

http://127.0.0.1:4444/dashboard/zalenium_2bea6f97-2053-4270-be53-5daa874e4fd8_firefox_LINUX_20180308114331063.mp4

by the way I tried same docker run command on MacOs, docker version 17.03.1-ce, I surprise that video is working, why?
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5

**Comment by diemol** [comment]
Hi @koala2012,

It just looks like the docker version you have on the host is just too old, by using the one inside the container things worked better. The specific detail I cannot really describe it.

Inside the container there is an nginx serving the resources, so I cannot really say what the first issue was.

I'll close this issue since things are actually working, if you have more questions, please join us in Slack :)

**Comment by koala2012** [comment]
@diemol Do you mean that I need to upgrade the docker ce version and have a try?

**Comment by diemol** [comment]
Well, it is better to have recent versions.
But if it works by passing the docker version flag you used, that should be enough I think,
