### ISSUE TITLE
Ability to start and stop video recording from the tests.

### ISSUE THREAD

**Issue by sri85** [zalando/zalenium#490]
We use protractor for our e2e tests , currently we are using vanilla selenium grid in our pipelines to run our tests but we are planning to switch to Zalenium (because its awesome) . We do run our tests in parallel and the way protractor runs the tests in parallel is that it shards the feature file and each feature file is run in a different browser. But the issue that we are having is when we record a video Zalenium creates one video file per feature file , but then this artifact might not be very useful when the developer views the video to debug the issue(Lets say if the feature file has 4 scenarios , if the third tests fails , the developer will need to see videos of first 3 scenarios which have passed)

Is there a way I could programmatically control the video recording via an API , if its available then possibly i could use a `cucumber` `AfterSceario` `BeforeScenario` hook to start and stop the video after every scenario

**Comment by iMbaundso** [comment]
Please have a look at https://github.com/zalando/zalenium/issues/471.

We're also using Protractor (jasmine instead of cucumber) with multicaps for our e2e tests and do not acquire a new Zalenium session between every scenario. We do however have an additional reporting which says which scenario has failed including the exception. This made it quite easy to fast forward the video to the interesting parts once you've done it a few times. 
Additionally we are doing a some kind of visually marking the first error using protractors browser.executeScript in a jasmine callback (we are making our page header red which makes it quite obvious to see at what point the test failed ;)). You could do something similar using cucumber hooks I guess (maybe have a look at some reporters as they are doing something similar)

Protractor snippet could look something like this:
browser.executeScript('document.querySelector(".header").style.background = red');

**Comment by diemol** [comment]
Hi @sri85 @iMbaundso @gpapadakis

Actually, I was thinking that we could do something about it for those types of tests. Maybe an alternative would be to keep using cookies to send custom commands to Zalenium (as when a test passes or a message is displayed on screen). Perhaps a cookie saying `new Cookie("zaleniumVideo", "START");` and `new Cookie("zaleniumVideo", "STOP");`.

It is just an idea, and I am kind of short of time these days since the free time I have, we are trying to improve the Kubernetes part. But if someone feels like implementing it, we would be very happy to accept PRs.

**Comment by sri85** [comment]
Thanks for the idea @diemol  ,  i will try to create a PR

**Comment by javacoldbrew** [comment]
Has there been any update on this?

**Comment by diemol** [comment]
Closing, as it is consolidated in #645
If development starts, we'll reopen the issue.

**Comment by gpapadakis** [comment]
No update on this yet @diemol?

**Comment by gpapadakis** [comment]
Ok @diemol then we will try to evaluate if we can get our engineering team to see if we can get some work on that

**Comment by aneslozo** [comment]
Any news on this one?

**Comment by rakeshnambiar** [comment]
@diemol Is this available now? I would like to see a separate view for each Test case and currently, it's difficult to differentiate the Test cases from the single video.

**Comment by diemol** [comment]
@rakeshnambiar no one has given us a hand 😞 
Would you like to give it a try?

**Comment by sri85** [comment]
@diemol  I tried finding the code which controls the video recording in zalenium project, but was unable to find it ? .. is video recording done as part of zalenium project, or is part of the https://github.com/elgalu/docker-selenium ?  
Can you please point me to the right direction?

**Comment by diemol** [comment]
@sri85 
This is where the video recording is started https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/DockerSeleniumRemoteProxy.java#L380 and here is where it is stopped.
https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/DockerSeleniumRemoteProxy.java#L750
