### ISSUE TITLE
Improve logging of zalenium

### ISSUE THREAD

**Issue by dennisgranath** [zalando/zalenium#498]
I would like to help out improving the logging of Zalenium to be able to visualise usage of Zalenium (and cloud remote). I have two alternative solutions on how to to this:

1. Add jul-to-slf4j to automatically send logs from java util logging framework to slf4j and use logback. 
 Using this solution we don't need to change any code inside zalenium in order to use logback.

2. Use slf4j directly. This requires code change to use slf4j api instead of java util logging. The logs from selenium can still be converted to logback via jul-to-slf4j.

After such a change is made we can optionally log in json format and use MDC (Mapped Diagnostic Context) to improve logging in zalenium (in a separate pull request). This will make it possible to make really nice dashboards to visualise usage in for example Kibana.

What do you say? Would you be interested in such a change? Which alternative would you prefer? Maybe you have another solution that I could help out with?

Keep up the good work!!

**Comment by diemol** [comment]
Hi @dennisgranath,

Thanks for the interest! We are up for any improvements of course :) Something that would be really nice in the end is to send the logs to Kibana (or something similar).

I remember I had some issues with slf4j, I wanted to use that one at the beginning, but some conflict with the logging in Selenium itself made things weird, so I just stayed with the Java util. I mean, the idea was to make it work and not to loose time with those small things... But now it sounds like a good moment to rework that part.

Which alternative? It mostly depends on how much time you have. I guess I'd prefer slf4j since it is just one step away to having logs in json format. But if you want to experiment first and avoid code changes, alternative Nr. 1 is also fine.

Thanks!

**Comment by peerster** [comment]
I also vote for solution number 2 👍
