### ISSUE TITLE
Cannot build docker for having no-sudo user, project.build.finalName variable for .jar file unavailable ZAL_VER="${project.build.finalName}" \ ${ZAL_VER}.jar 

### ISSUE THREAD

**Issue by FantomX1** [zalando/zalenium#535]
Cannot build docker for having no-sudo user, project.build.finalName variable for .jar file unavailable
ZAL_VER="${project.build.finalName}" \ ${ZAL_VER}.jar 

Zalenium Image Version(s):  
Current master

Docker Version:  

If using docker-compose, version:  

OS: 
Windows 10

Docker Command to start Zalenium:  
Start within openshift

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
I can build Dockerfile so that I have no-sudo user for openshift

## Actual Behavior -
I put the newest docker image from dockerhub into openshift, tried two different user versions from github, it needs sudo-less user

**Comment by diemol** [comment]
Hi @FantomX1,

In theory, Zalenium should work in OpenShift without sudo right away, since in the past we spent quite some time tweaking the startup scripts. Did you have problems starting it?

In addition, if you want to build the image yourself, the easiest way is to do:
`mvn clean package -DskipTests=true -Pbuild-docker-image`

**Comment by diemol** [comment]
More detailed instructions can be found here: https://zalando.github.io/zalenium/#contributing

**Comment by pearj** [comment]
@FantomX1 your problem is because you tried to build the docker container without running the Maveb build first. After that you can then the the docker build in the `target` directory.

**Comment by pearj** [comment]
At the moment you can’t use source to image to build Zalenium inside OpenShift. You need to do a binary build. 

On my windows 10 machine I run:

```
mvn clean verify -DskipTests
oc start-build zalenium —from-dir=target —follow
```

**Comment by pearj** [comment]
Your problem is that it needs permissions inside OpenShift to be able to create pods etc. We have a custom role that we grant to the zalenium service account to make it work. 

I’ve been updating the OpenShift template on a branch which is fairly feature complete. It at least should show you what you’re missing. 

https://github.com/pearj/zalenium/blob/031fd96c08226badffcb2be0cea114209af7f147/docs/k8s/zalenium-template.yaml

Or if you just want to make it simple and your running with the default service account. You can grant the `admin` role to the `default` service account. 

I think it’s something like `oc adm policy add-role-to-user admin -z default` then restart the zalenium container.  Just use the Docker hub version.

**Comment by diemol** [comment]
Hi @FantomX1,  are you still having issues with the deployment? If so, perhaps you can join us at https://seleniumhq.herokuapp.com/, channel #zalenium, so things can move a bit faster for you.

**Comment by FantomX1** [comment]
@diemol 
Thank you, will give it a check in nearest time hopefully

**Comment by diemol** [comment]
Closing this issue since we didn't get more feedback from the OP.

If the issue still persists please create a new issue with updated data/info.
