### ISSUE TITLE
Zalenium is not starting with -e SELENIUM_NODE_PARAMS="-maxSession 3" parameter

### ISSUE THREAD

**Issue by poison2332** [zalando/zalenium#536]
Zelenium is not starting with -e SELENIUM_NODE_PARAMS="-maxSession 3" parameter
Also with some parameters zalenium starting, but there is no impact.
Zalenium Image Version(s):  
- latest 
Docker Version:  17.09.0-ce

OS:  Windows 10
Docker Command to start Zalenium:  
sudo docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -e SELENIUM_NODE_PARAMS="-maxSession 3" --privileged dosel/zalenium start --debugEnabled true

## Expected Behavior -
Zalenium started. Node config '-maxSession' changed to 3
## Actual Behavior -
Zalenium is not started
[maxSessionTurnedOn.txt](https://github.com/zalando/zalenium/files/1942037/maxSessionTurnedOn.txt)

**Comment by diemol** [comment]
Hi @poison2332,

Sorry for the late reply.

The reason why it won't work as expected is because the containers/nodes created on the fly to run tests will only have one test slot (so only one session max will be executed concurrently). 

We do this to simplify the test handling and video recording. If more than one test was allowed to be executed at the same time in a given container, the video would have many tests running and the end result would be useless. 

Is that what you were trying to achieve? Run more than one test concurrently per container/node?

**Comment by diemol** [comment]
Hi @poison2332,

It seems like it is a matter of handling the WebDriver instances you are creating in the test.

The bottomline is that starting Zalenium with `SELENIUM_NODE_PARAMS="-maxSession 3"` would not work since it only uses one browser per container/node. In addition, you could also follow @pearj's comment above to have the amount of nodes you desire.

I will close this issue since there was no straight clear bug on Zalenium's side. If you have more questions, please join us in the #zalenium channel on https://seleniumhq.herokuapp.com/ (which is also the main Slack/IRC channel for Selenium).
