### ISSUE TITLE
Adding video recording to a Selenium Proxy

### ISSUE THREAD

**Issue by javacoldbrew** [zalando/zalenium#566]
I have a remote desktop running Windows 7.

To attach IE to Selenium Grid, I run:
java -jar -Dwebdriver.internetexplorer.driver=C:\Selenium\3.11.0\server\IEDriverServer.exe selenium-server-standalone-3.11.0.jar -role webdriver -port 5554 -hub http://<IP>:4444/grid/register -browser browserName="internet explorer",version=11.0.9600.18977,platform=WINDOWS

With this I am able to run tests but, I was wondering how would you make it so Zalenium records video.

I tried to pass the servlets by adding:

-servlets de.zalando.ep.zalenium.servlet.LivePreviewServlet 
-servlets de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet 
-servlets de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet
-servlets de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet 
-servlets de.zalando.ep.zalenium.dashboard.DashboardInformationServlet
-servlets de.zalando.ep.zalenium.servlet.VncAuthenticationServlet

But I get an error message saying that they cannot be instantiated.
<img width="882" alt="ieonthegrid" src="https://user-images.githubusercontent.com/25971275/39838318-170f6300-53a7-11e8-8c21-a255341e4bc0.PNG">

**Comment by pearj** [comment]
Zalenium can only record videos for the containers that it starts itself using the elgalu/selenium container. Because those containers have the video recording capability inside them.  Zalenium, the grid isn’t the thing doing the video recording, it is the selenium node. 
So it’s not possible to do what you want. 
If you use a 3rd party testing provider such as browser stack, they provide video recording for all browser types. But the video won’t be copied back to zalenium, you’ll have to video the video in their UI.

**Comment by diemol** [comment]
Thanks @pearj for replying!
Just to clarify the video part with cloud providers, actually Zalenium fetches the video from the cloud provider and adds it to the dashboard.

But yes, everything is like that. The video recording feature only works with the containers.

**Comment by javacoldbrew** [comment]
Thanks for letting me know! I will look into using a 3rd party then.
