### ISSUE TITLE
keepOnlyFailedTests only logs failed tests

### ISSUE THREAD

**Issue by joaocfernandes** [zalando/zalenium#599]
## Zalenium Image Version(s):  
3.12.0b
dosel/zalenium   c32f44676e9f        5 days ago          793MB

## Docker Version: 
Docker version 17.12.1-ce, build 7390fc6

## Docker Compose:
docker-compose version 1.19.0, build 9e633ef

## OS: 
Ubuntu 4.13.0-1018-azure

## Docker Command to start Zalenium:  
docker-compose up -d

## Part of docker-compose.yaml config:

```
command: >
      start --screenWidth 1600 --screenHeight 1200
            --timeZone "Europe/Lisbon"
            --maxTestSessions 5 --desiredContainers 4 --maxDockerSeleniumContainers 8
            --keepOnlyFailedTests true --sendAnonymousUsageInfo false
            --sauceLabsEnabled false
            --browserStackEnabled true
            --testingBotEnabled false
            --startTunnel true

```

## Expected Behavior -
According to the documentation the flag --keepOnlyFailedTests - Keeps only videos of failed tests (you need to send a cookie with the test result).

When using keepOnlyFailedTests flag set to true I expected that all the tests would be logged on the dashboard. Passed tests would have a Selenium Log but wouldn't have a video attached but failed tests would have both the video and the Selenium Log.

## Actual Behavior -
Only Failed or timeout tests are logged on the dashboard.

![zalenium](https://user-images.githubusercontent.com/2494410/40617716-1c6fc418-6287-11e8-9b76-3ecdb064dcc2.png)

## Comment
The name of the flag and the behavior are consistent. e.g It only keeps failed tests on the dashboard.
According to the documentation the flag is only specific to the video retention policy.
If you agree with the described expected behavior,  can you point me where does this decision happens after the video encoding? I would be happy to try a PR.

**Comment by diemol** [comment]
Hi @joaocfernandes,

Sorry for the delayed reply.

To be honest, when we built the feature it was meant to keep information related to the failed tests, so people could add them to their test reports. I understand that one can go more into detail and say that the rest of the tests should be shown without video, but the feature is only about keeping information from failed tests.

We also thought that keeping information from the passed tests does not help so much, because the only information present would be the logs. Logs are not so interesting when tests passes. 

The dashboard is meant to be as a complement to the current reporting structure that users may have with their existing test suite, it should not replace the test report.

So no, this would not be something we want to add since the value it adds is not really significative.

Thanks for using Zalenium and for raising this issue!

If you feel that the docs should be improved to make it more clear, please feel free to send us a PR.

**Comment by joaocfernandes** [comment]
Hi @diemol ,

Thanks for your response. I understand your point. I have created a PR #605  with a small change to the flag description.

Best Regards,
