### ISSUE TITLE
Browserstack credentials aren't being set

### ISSUE THREAD

**Issue by micheletest** [zalando/zalenium#620]
Zalenium Image Version(s):  
3.11.0h

I am trying to send tests to zalenium, deployed on Kubernetes, to be forwarded to Browserstack. I have `browserStackEnabled` and set up the env with `BROWSER_STACK_USER` and `BROWSER_STACK_KEY`.  I can log into the zalenium pod and see that these are set properly and match my credentials on Browserstack.

on the zalenium deployment
```
$ env | grep BROWSER
BROWSER_STACK_WAIT_TIMEOUT=2m
BROWSER_STACK_TUNNEL_OPTS=-skipCheck -v -forcelocal
BROWSER_STACK_KEY=REDACTED
BROWSER_STACK_TUNNEL=false
BROWSER_STACK_TUNNEL_ID=zalenium
BROWSER_STACK_USER=REDACTED
```
Unfortunately, I get an error, as if the Browserstack credentials are not set up.

```py.test -rws -k chrome_iphone --base-url https://better.com  --driver Remote --host REDACTED:REDACTED@zalenium --html=test-report-chrome_iphone.html --self-contained-html --variables cap_safari11_high_sierra.json
======================================================================================= test session starts ========================================================================================
platform linux -- Python 3.6.3, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
driver: Remote
sensitiveurl: \b(http|https):\/\/better\.com *** WARNING: sensitive url matches https://better.com ***
baseurl: https://better.com
rootdir: /buildkite/builds/buildkite-agent-2495154159-k84ph/better/selenium-cross-browser/mortgage/selenium, inifile: pytest.ini
plugins: xdist-1.22.2, variables-1.7.1, timeout-1.2.1, selenium-1.12.0, rerunfailures-4.0, metadata-1.7.0, html-1.17.0, forked-0.2, base-url-1.4.1
timeout: 180.0s method: signal
collected 69 items / 68 deselected

tests/homepage/test_home_page_cta.py E                                                                                                                                                       [100%]

============================================================================================== ERRORS ==============================================================================================
___________________________________________________________________________ ERROR at setup of test_home_page_cta_mobile ____________________________________________________________________________

request = <SubRequest 'driver' for <Function 'test_home_page_cta_mobile'>>, driver_class = <class 'selenium.webdriver.remote.webdriver.WebDriver'>
driver_kwargs = {'browser_profile': None, 'command_executor': 'http://REDACTED:REDACTED@zalenium:4444/wd/h...': {'browser': 'Safari', 'browser_version': '11.0', 'browserstack.debug': True, 'browserstack.networkLogs': True, ...}}

    @pytest.yield_fixture
    def driver(request, driver_class, driver_kwargs):
        """Returns a WebDriver instance based on options and capabilities"""
>       driver = driver_class(**driver_kwargs)

/usr/lib/python3.6/site-packages/pytest_selenium/pytest_selenium.py:130:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:154: in __init__
    self.start_session(desired_capabilities, browser_profile)
/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:243: in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f8e388395c0>
response = {'status': 401, 'value': '{"value":{"message":"Invalid username or password"},"sessionId":"","status":13}'}

    def check_response(self, response):
        """
            Checks that a JSON response from the WebDriver does not have an error.

            :Args:
             - response - The JSON response from the WebDriver server as a dictionary
               object.

            :Raises: If the response contains an error message.
            """
        status = response.get('status', None)
        if status is None or status == ErrorCode.SUCCESS:
            return
        value = None
        message = response.get("message", "")
        screen = response.get("screen", "")
        stacktrace = None
        if isinstance(status, int):
            value_json = response.get('value', None)
            if value_json and isinstance(value_json, basestring):
                import json
                try:
                    value = json.loads(value_json)
                    if len(value.keys()) == 1:
                        value = value['value']
                    status = value.get('error', None)
                    if status is None:
                        status = value["status"]
                        message = value["value"]
                        if not isinstance(message, basestring):
                            value = message
                            message = message.get('message')
                    else:
                        message = value.get('message', None)
                except ValueError:
                    pass

        exception_class = ErrorInResponseException
        if status in ErrorCode.NO_SUCH_ELEMENT:
            exception_class = NoSuchElementException
        elif status in ErrorCode.NO_SUCH_FRAME:
            exception_class = NoSuchFrameException
        elif status in ErrorCode.NO_SUCH_WINDOW:
            exception_class = NoSuchWindowException
        elif status in ErrorCode.STALE_ELEMENT_REFERENCE:
            exception_class = StaleElementReferenceException
        elif status in ErrorCode.ELEMENT_NOT_VISIBLE:
            exception_class = ElementNotVisibleException
        elif status in ErrorCode.INVALID_ELEMENT_STATE:
            exception_class = InvalidElementStateException
        elif status in ErrorCode.INVALID_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR \
                or status in ErrorCode.INVALID_XPATH_SELECTOR_RETURN_TYPER:
            exception_class = InvalidSelectorException
        elif status in ErrorCode.ELEMENT_IS_NOT_SELECTABLE:
            exception_class = ElementNotSelectableException
        elif status in ErrorCode.ELEMENT_NOT_INTERACTABLE:
            exception_class = ElementNotInteractableException
        elif status in ErrorCode.INVALID_COOKIE_DOMAIN:
            exception_class = InvalidCookieDomainException
        elif status in ErrorCode.UNABLE_TO_SET_COOKIE:
            exception_class = UnableToSetCookieException
        elif status in ErrorCode.TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.SCRIPT_TIMEOUT:
            exception_class = TimeoutException
        elif status in ErrorCode.UNKNOWN_ERROR:
            exception_class = WebDriverException
        elif status in ErrorCode.UNEXPECTED_ALERT_OPEN:
            exception_class = UnexpectedAlertPresentException
        elif status in ErrorCode.NO_ALERT_OPEN:
            exception_class = NoAlertPresentException
        elif status in ErrorCode.IME_NOT_AVAILABLE:
            exception_class = ImeNotAvailableException
        elif status in ErrorCode.IME_ENGINE_ACTIVATION_FAILED:
            exception_class = ImeActivationFailedException
        elif status in ErrorCode.MOVE_TARGET_OUT_OF_BOUNDS:
            exception_class = MoveTargetOutOfBoundsException
        elif status in ErrorCode.JAVASCRIPT_ERROR:
            exception_class = JavascriptException
        elif status in ErrorCode.SESSION_NOT_CREATED:
            exception_class = SessionNotCreatedException
        elif status in ErrorCode.INVALID_ARGUMENT:
            exception_class = InvalidArgumentException
        elif status in ErrorCode.NO_SUCH_COOKIE:
            exception_class = NoSuchCookieException
        elif status in ErrorCode.UNABLE_TO_CAPTURE_SCREEN:
            exception_class = ScreenshotException
        elif status in ErrorCode.ELEMENT_CLICK_INTERCEPTED:
            exception_class = ElementClickInterceptedException
        elif status in ErrorCode.INSECURE_CERTIFICATE:
            exception_class = InsecureCertificateException
        elif status in ErrorCode.INVALID_COORDINATES:
            exception_class = InvalidCoordinatesException
        elif status in ErrorCode.INVALID_SESSION_ID:
            exception_class = InvalidSessionIdException
        elif status in ErrorCode.UNKNOWN_METHOD:
            exception_class = UnknownMethodException
        else:
            exception_class = WebDriverException
        if value == '' or value is None:
            value = response['value']
        if isinstance(value, basestring):
            if exception_class == ErrorInResponseException:
                raise exception_class(response, value)
            raise exception_class(value)
        if message == "" and 'message' in value:
            message = value['message']

        screen = None
        if 'screen' in value:
            screen = value['screen']

        stacktrace = None
        if 'stackTrace' in value and value['stackTrace']:
            stacktrace = []
            try:
                for frame in value['stackTrace']:
                    line = self._value_or_default(frame, 'lineNumber', '')
                    file = self._value_or_default(frame, 'fileName', '<anonymous>')
                    if line:
                        file = "%s:%s" % (file, line)
                    meth = self._value_or_default(frame, 'methodName', '<anonymous>')
                    if 'className' in frame:
                        meth = "%s.%s" % (frame['className'], meth)
                    msg = "    at %s (%s)"
                    msg = msg % (meth, file)
                    stacktrace.append(msg)
            except TypeError:
                pass
        if exception_class == ErrorInResponseException:
            raise exception_class(response, message)
        elif exception_class == UnexpectedAlertPresentException:
            alert_text = None
            if 'data' in value:
                alert_text = value['data'].get('text')
            elif 'alert' in value:
                alert_text = value['alert'].get('text')
            raise exception_class(message, screen, stacktrace, alert_text)
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.WebDriverException: Message: Invalid username or password

/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
```

On the zalenium side, here is the log:
```18:50:09.637 [Matcher thread] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Test will be forwarded to BrowserStack, {os=OS X, browser=Safari, os_version=High Sierra, browserstack.networkLogs=true, name=test_home_page_cta_mobile, browser_version=11.0, resolution=1280x1024, browserstack.debug=true}
18:50:09.637 [Matcher thread] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {browserName=BrowserStack, maxInstances=4, platformName=ANY}
18:50:09.637 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key 1c07d02a-2244-4945-8512-c70ac3115e46 assigned to remote () after 0 seconds (4 ms).
18:50:09.640 [Forwarding 1c07d02a-2244-4945-8512-c70ac3115e46 (int. key, remote not contacted yet.) to http://hub-cloud.browserstack.com:80/wd/hub at 6:50:09 PM] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Currently using 1 parallel sessions towards BrowserStack. Attempt to start one more.
```

Thanks for any help in getting this to work.

**Comment by pearj** [comment]
@micheletest my guess is that you're using the wrong credentials. You don't use your browserstack username and password here, you use the automation username and access key.

You can find it here: https://automate.browserstack.com/

If you want to get the local tunnel going have a read of #575

**Comment by micheletest** [comment]
I'm using the correct credentials. The issue here is that using python, the user and key capabilities cannot be passed to Browserstack. According to their support:

`It seems it is not possible to trigger Remote URL with username and key using the capabilities. You need to pass them in the URL itself.`

I can confirm that the library I use - pytest-selenium - does pass the user and key via the URL when given a Browserstack driver, so changing zalenium to do the same would fix this issue. I would like to send my Browserstack tests through zalenium if possible.

I reached back out to Browserstack to understand why everyone doesn't appear to have this issue and  and it seems this is an issue with python.  According to them, for java:  

`I have tried in Java, it works by sending the Automate credentials via Capability.`

They are going to check why there is a difference. I'll update here.

**Comment by pearj** [comment]
@micheletest you shouldn't need to put the user and key as capabilities on the test, they're supposed to be environment variables on your zalenium container like you mentioned in the original description.  Not sure why it isn't working for you, as it seems like you don't have the tunnel enabled. Because for the tunnel to work you do need to set a capability for the tunnel id.

**Comment by micheletest** [comment]
@pearj I am setting the env variables on the container. Specifically:  `BROWSER_STACK_USER` and `BROWSER_STACK_KEY`. I can log into the zalenium deployment and verify they are set and correct. I'm using the Automate user and password, which I actually use elsewhere, so I know that they work in other contexts, just not via zalenium.

I don't think I need a tunnel, I'm hitting a public website so it shouldn't be necessary.

Still also working with Browserstack support to figure this out.

**Comment by natkrish** [comment]
@I am having the same issue when trying to run on browserstack. Can you let me know whats the capability to set to identify zalenium? 
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
........15:27:33.212 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.12.0', revision: 'unknown'
15:27:33.219 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.....15:27:34.301 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
15:27:34.301 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Autostarting container, because 0 is less than min 2
...15:27:35.025 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
.15:27:35.310 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
15:27:35.312 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.17.0.2:4445/grid/register/
15:27:35.313 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.17.0.2:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Starting Browser Stack node...
.........15:27:38.304 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium build info: version: '3.12.0', revision: 'unknown'
15:27:38.322 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching a Selenium Grid node on port 30002
..15:27:38.945 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_nIB1eK] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSaving
s=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,
startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
15:27:38.953 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_nIB1eK, containerId=9a45c34a11abfcc37d9a84cd52e59a490b5c4a000c23360397968ec2c
9ae2615, nodePort=40000].
15:27:39.065 [main] INFO  o.o.s.remote.server.SeleniumServer - Selenium Server is up and running on port 30002
15:27:39.065 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium Grid node is up and ready to register to the hub
15:27:39.170 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - Registering the node to the hub: http://localhost:4444/grid/register
.15:27:40.222 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_wNahhP] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings
=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,s
tartTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
15:27:40.222 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_wNahhP, containerId=ae3fec611b1fde68014e19fa036fdf2c09198efa8f38d85fa7cd7866c
830c387, nodePort=40001].
.........15:27:43.004 [qtp360936478-16] INFO  d.z.e.z.p.BrowserStackRemoteProxy - [BS] Getting account max. concurrency from https://www.browserstack.com/automate/plan.json
15:27:43.063 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://hub-cloud.browserstack.com:80
15:27:43.114 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - Updating the node configuration from the hub
15:27:43.390 [main] INFO  o.o.g.i.utils.SelfRegisteringRemote - The node is registered to the hub and ready to use
Browser Stack node started!
Starting BrowserStackLocal...
Waiting for BrowserStack tunnel to start...
.....................BrowserStack tunnel started! (wait-browserstack.sh)
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
15:27:57.810 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_wNahhP started after 17588.
15:27:58.728 [Thread-12] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001
15:27:58.731 [Thread-13] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
15:27:58.733 [Thread-12] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container ae3fec611b1fde68014e19fa036fdf2c09198efa8f38d85fa7cd7866c830c387 http://172.17.0.4:40001.
15:27:58.740 [Thread-13] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container 9a45c34a11abfcc37d9a84cd52e59a490b5c4a000c23360397968ec2c9ae2615 http://172.17.0.3:40000.
15:27:59.003 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_nIB1eK started after 20050.
15:28:10.923 [qtp360936478-17] INFO  o.o.g.w.s.handler.RequestHandler - Got a request to create a new session: Capabilities {browserName: safari, safari.options: {technologyPreview: false}}
15:28:10.928 [qtp360936478-17] INFO  d.z.e.z.registry.ZaleniumRegistry - Adding sessionRequest for {browserName=safari, safari.options={technologyPreview=false}}
15:28:10.940 [Matcher thread] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Test will be forwarded to BrowserStack, {browserName=safari, safari.options={technologyPreview=false}}
15:28:10.942 [Matcher thread] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {browserName=BrowserStack, maxInstances=10, platformName=ANY}
15:28:10.946 [Matcher thread] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key 7d101c38-78ed-42e7-b9cc-a3e3d87c6915 assigned to remote () after 0 seconds (195 ms).
15:28:10.977 [Forwarding 7d101c38-78ed-42e7-b9cc-a3e3d87c6915 (int. key, remote not contacted yet.) to http://hub-cloud.browserstack.com:80/wd/hub at 3:28:10 PM] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Currently using 1 paralle
l sessions towards BrowserStack. Attempt to start one more.

**Comment by pearj** [comment]
@natkrish I’m not sure what your problem is? I don’t see errors in the logs you posted? Are you trying to use a BrowserStack tunnel?

**Comment by micheletest** [comment]
I'm still having this issue. I tried to set the new env variable `BROWSER_STACK_URL` with my username and access key and it still does not work. The url that is created though, is exactly the same as is suggested within the Browser Stack docs. (They fill in the username and access key to give a sample if you are logged into their site. ) Still working with Browser Stack support to see if it's on their end or at least give me more information on what is being passed to them on session start.

```20:48:57.023 [Forwarding 5886e6a0-1439-49c5-aef6-991df542ab5f (int. key, remote not contacted yet.) to http://<redacted-user>:<redacted-key>@hub-cloud.browserstack.com:80/wd/hub at 8:48:57 PM] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Currently using 1 parallel sessions towards BrowserStack. Attempt to start one more.```

results in: 
`E       selenium.common.exceptions.WebDriverException: Message: Invalid username or password`

**Comment by pearj** [comment]
I think your best bet now is packet capture. Use browser stack directly with your test and then use zalenium and try and see what might be happening to the credentials.

**Comment by micheletest** [comment]
@diemol @pearj  I am not going to have time to look at this for quite a while. I don't want to litter the issues here, so this is ok with me to close for now. I can take a look and retry this later, including your suggestions and if I still have issues, reopen, or create a new issue.

**Comment by diemol** [comment]
Thanks for replying @micheletest, closing for now then.

**Comment by rburgos240** [comment]
I'm encountering the same issue with Zalenium not routing test requests to be fulfilled by Browserstack. It seems to only happen when basic auth is enabled on Zalenium. 


```
zalenium    | 00:12:28.058 [qtp778162712-18] INFO  o.o.g.w.s.handler.RequestHandler - Got a request to create a new session: Capabilities {browserName: MicrosoftEdge, cssSelectorsEnabled: true, javascriptEnabled: true, nativeEvents: false, platform: WINDOWS, rotatable: false, takesScreenshot: true, version: }
zalenium    | 00:12:28.063 [qtp778162712-18] INFO  d.z.e.z.registry.ZaleniumRegistry - Adding sessionRequest for {rotatable=false, nativeEvents=false, browserName=MicrosoftEdge, takesScreenshot=true, javascriptEnabled=true, version=, cssSelectorsEnabled=true, platform=WINDOWS}
zalenium    | 00:12:28.073 [BrowserStack] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Test will be forwarded to BrowserStack - {rotatable=false, nativeEvents=false, browserName=MicrosoftEdge, takesScreenshot=true, javascriptEnabled=true, version=, cssSelectorsEnabled=true, platform=WINDOWS}
zalenium    | 00:12:28.074 [http://172.19.0.3:40000] INFO  org.openqa.grid.internal.TestSlot - Trying to create a new session on test slot {browserName=BrowserStack, maxInstances=1, platformName=ANY}
zalenium    | 00:12:28.082 [http://172.19.0.3:40000] INFO  d.z.e.z.registry.ZaleniumRegistry - Test session with internal key ecf9c524-7c70-4c78-8f8c-f2c63007a8c9 assigned to remote (http://172.19.0.2:30002) after 0 seconds (167 ms).
zalenium    | 00:12:28.098 [BrowserStack] INFO  d.z.e.z.p.CloudTestingRemoteProxy - Currently using 1 parallel sessions . Trying to start one more.
```

**Comment by micheletest** [comment]
I can confirm that I had basic auth enabled when I encountered this issue too.

**Comment by rburgos240** [comment]
I've also tested with Saucelabs and was still prevented from creating a browser session in Saucelab's grid via Zalenium with basic auth enabled. Sauce labs did however return a more detailed response which shows the real issue. Zalenium is passing its basic auth credentials when tests are routed to cloud browser providers. 

```
Selenium::WebDriver::Error::WebDriverError (unexpected response, code=401, content-type="text/plain")
Misconfigured -- Sauce Labs Authentication Error.
You used username 'REDACTED' and access key 'REDACTED' to authenticate, which are not valid Sauce Labs credentials.

The following desired capabilities were received:
{'accessKey': 'REDACTED',
 'browserName': 'MicrosoftEdge',
 'cssSelectorsEnabled': True,
 'javascriptEnabled': True,
 'nativeEvents': False,
 'platform': 'WINDOWS',
 'rotatable': False,
 'server:CONFIG_UUID': None,
 'takesScreenshot': True,
 'username': 'REDACTED',
 'version': ''}
```

**Comment by diemol** [comment]
That is a good find! It makes sense that it fails since the auth credentials might be mixed with the ones from the cloud service. I'll create a new issue based on the comment.
