### ISSUE TITLE
Feature Request: ability to specify the container to spawn based on the browser capability required for a test

### ISSUE THREAD

**Issue by raffaelespazzoli** [zalando/zalenium#650]
based on my understanding of the doc there is a way to specify which image to be used for the selenium slave nodes using the `-seleniumImageName`.
From my understanding, that image will be used for all the requests and therefore it needs to be able to meet all the possible browser capabilities requested for the tests. 
This may mean larger and more difficult-to-maintain images, but also may make it impossible to run tests on both Linux and Windows containers/browser. 
This scenario is becoming technically possible now that Kubernetes / Openshift support windows nodes.
Ideally there should be a way to pass a configuration to the Zalenium hub container so that is spawn a specific container based on a specific browser capability (or set of capabilities).

**Comment by diemol** [comment]
Hi @raffaelespazzoli,

This is a huge request, and it goes in the same line of supporting IE/Edge browsers in docker and so on.

I was not aware that now k8s supports Windows nodes, nevertheless I still image that a pod needs to be started to run the test. This pod should be able to run a Windows OS to run tests with IE/Edge, right? I am not sure if that is possible yet. If so, please help us building that and send us a PR.

For now, and with the current things that I am aware, it is not possible to implement that. If I am wrong, again, please help us and send us a PR with a possible solution.

I'll close this issue, but feel free to comment if a solution is found.

**Comment by raffaelespazzoli** [comment]
not sure why this was closed. 
I disagree with this decision.
This was not a request to support the whole windows container use case.
This was a request to support a much smaller use case that is necessary for the windows container one, but that has also some other immediate benefits,
This request was simply to being able to pass additional metadata to the capability request of a test.
This metadata would indicate the docker image to instantiate to run that test.
I am thinking something along these lines:
``` multiCapabilities: [{
	  'browserName': 'firefox',
          'image': 'myfirefoximage'
	}, {
	  'browserName': 'chrome',
          'image': 'mychromeimage'
	}],
```
what zalenium should do is to inspect the image filed and instantiate the corresponding container. 
today only one image is supported and it is not realistic for an enterprise deployment in my opinion.

**Comment by pearj** [comment]
@raffaelespazzoli I have heard something about k8s being able to run windows containers, but docker on windows cannot run graphical applications yet, ie a browser.  So windows support is impossible for the moment.

See: 
* https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/214
* https://windowsserver.uservoice.com/forums/304624-containers/suggestions/17506354-provide-an-internet-explorer-docker-container-ena

I'm not sure what being able to specify multiple images has to do with enterprise capability though, as zalenium is already used in the enterprise as is docker-selenium.

It sounds like you're asking zalenium to become a drop-in replacement for cloud testing providers like browserstack.  Where you can choose multiple combinations of operating systems, browsers and browser versions.

As discussed above different operating systems is not possible, because only linux UI can be containerised at present. Multiple browser versions are requested from time to time, but supporting the actual docker containers for various versions of browsers is quite a huge undertaking, as selenium has hooks into chrome and firefox for automation, so certain versions of selenium only work with certain versions of chrome and firefox.  So who would maintain that? You? It's not something any of the maintainers have time for.

Also, in my opinion, specifying that your web application only works with a specific version of firefox and chrome in this day and age is not really a good approach, as browsers update themselves automatically and quite often (maybe not in the enterprise, but I think this is poor practise anyway...).

So sure, if you want to maintain a whole suite docker images and want to contribute the code to allow different docker images based on requested capabilities, then we'd most likely accept your PR. But it's not something any of the regular maintainers want, and therefore unlikely to implement in any meaningful timeframe as there are already quite a few other [feature requests](#654).
