### ISSUE TITLE
How to import a file from a local folder to zalenium docker container?

### ISSUE THREAD

**Issue by Muraligowtham** [zalando/zalenium#658]
Hi Team,
I am trying to import a file from my local machine folder to docker zalenium container, But I couldn't successfully do it by adding a -v <Source>: <destination > option, since we have lot test cases that needs this feature, it will be really helpful, if you can get us some work around / special instructions on how to do it.

I tried this and it didn't work,
sudo docker run --rm --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -v /Certificates:/Certificates  --privileged dosel/zalenium start --desiredContainers 1 --sendAnonymousUsageInfo false --timeZone "America/New_York"

OS : CentOS
Pls let me know the mistake that I am doing here

**Comment by pearj** [comment]
I presume this means you're trying to map files into the actual salenium containers (not the zalenium one)?

If this is the case search for "Mounting volumes/folders across containers" on this page: https://opensource.zalando.com/zalenium/

**Comment by diemol** [comment]
Hi @Muraligowtham,

Please follow @pearj's recommendation, check the docs where it is clear how to mount folders and files across all containers.

Keep in mind that if you want to mount certificates, you'll probably need to build your own custom elgalu/selenium image.

If you need more help and details, please join us in the #zalenium channel at https://seleniumhq.herokuapp.com/.

I'll close this issue since we can answer these type of questions in the Slack channel.
