### ISSUE TITLE
The site can't be reached error

### ISSUE THREAD

**Issue by restagner** [zalando/zalenium#748]
Zalenium Image Version(s):  
latest as of October 19, 2018
Docker Version:  
18.06.1-ce

OS: 
Linux
Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 \
      -e PULL_SELENIUM_IMAGE=true \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start

## Expected Behavior -

The browser should be able to reach the application under test (http://dev-rerun2.x.y.z.com)

## Actual Behavior -

The site can't be reached from within the container (see attached screenshot from a Zalenium video session). What am I missing? OR, what am I doing wrong here?

![screenshot_20181019_064058](https://user-images.githubusercontent.com/798521/47223234-9afd7d00-d36d-11e8-8d00-14c215226b3c.png)

**Comment by dkder3k** [comment]
Hi @restagner 
As I understand http://dev-rerun2.x.y.z.com is available from you local machine so you could see if it is specified in /etc/hosts file. In this case you could use `--add-host="<ip address>"` key to add target ip address to containers hosts file.
Also you could explicitly specify network mode for docker `--network="bridge"` (you could try `host` instead of `bridge`)
See [docker documentation](https://docs.docker.com/engine/reference/run/#network-settings) for more

**Comment by diemol** [comment]
Thanks @dkder3k for replying! Actually, that makes a lot of sense. @restagner have you checked that?

**Comment by restagner** [comment]
@dkder3k

Yes, adding `--add-host="<ip address>"` as you suggested worked for me.  Thanks

**Comment by diemol** [comment]
Thanks for confirming that it works @restagner
