### ISSUE TITLE
Download Files From Nodes 

### ISSUE THREAD

**Issue by lmagana1992** [zalando/zalenium#754]
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  

Docker Version:  17.06

If using docker-compose, version:  

OS: Centos7

Docker Command to start Zalenium:  
 docker run --rm -ti -d --name zalenium -p 4444:4444 \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /tmp/videos:/home/seluser/videos \
--privileged dosel/zalenium start --gridUser admin --gridPassword password

## Feature Request -

We are currently using Zalenium to do UI testing of an Enterprise Tax Accounting Data Preparation software, in some of our tests we download files directly from the UI into the Virtual Environments and perform comparisons to baselines. We'd like know if there is a way to download the files directly from the containers where the tests are running? If that's not the case would it be possible to create an API call to obtain such files?

**Comment by diemol** [comment]
Hi @lmagana1992,

Please check "Mounting volumes/folders across containers" in the [docs](https://opensource.zalando.com/zalenium/). With that you can mount the downloads directory for each browser.

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com) where the community can help you as well.
