### ISSUE TITLE
novnc extension connector with other external nodes not in containers

### ISSUE THREAD

**Issue by daverod24** [zalando/zalenium#755]
Hi, I would like to have the possibility, I do not know if I already have or can integrate that if I have an external node in Windows, for example, that is registered in the zalenium, it can be seen in "http://10.0.0.1/grid/admin/live" and in the dashboard with novnc and take evidence in the same way as in containers

## Zalenium Image Version(s):  
3   latest
304 MB
9 days ago

## Docker Version:  
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-74.git6e3bb8e.el7.x86_64
 Go version:      go1.9.2
 Git commit:      6e3bb8e/1.13.1
 Built:           Wed Aug  1 16:56:40 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-74.git6e3bb8e.el7.x86_64
 Go version:      go1.9.2
 Git commit:      6e3bb8e/1.13.1
 Built:           Wed Aug  1 16:56:40 2018
 OS/Arch:         linux/amd64
 Experimental:    false

## Docker Command to start Zalenium:  
docker run  -tid --name zalenium -p 4444:4444 -p 4445:4445  -p 5555:5555 -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos -e zalenium_http_proxy="http://10.0.0.3:3128" \
  -e zalenium_https_proxy="http://10.0.0.3:3128" \
  -e zalenium_no_proxy="localhost,127.0.0.1,10.0.0.3" \
  --privileged dosel/zalenium start --desiredContainers 0 --maxDockerSeleniumContainers 0

## Expected behavior -
I can raise my node in windows and when I run the test I can see it from "http://10.0.0.1/grid/admin/live" and in the dashboard

## Real behavior -
I can not do it since the connector is only working for selenium node containers

thanks in advance

regards

**Comment by diemol** [comment]
Hi @daverod24,

This is expected since the implementation only does that for the containers created via Zalenium. 

If you would like to have the Windows node in it, have a look at the `LivePreviewServlet` class and work out the logic to add them. 

Of course, a proper setup in the Windows nodes is needed, with VNC and noVNC (or similar).

Additionally, this is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com) where the community can help you as well.
