### ISSUE TITLE
Question about distant server

### ISSUE THREAD

**Issue by loic-lopez** [zalando/zalenium#813]
Hello,

I would like to know if it is possible to reach for example: `http://domain.tld:4444/grid/admin/live`
as a distant dedicated server?

Thanks for reply.

**Comment by diemol** [comment]
Hi @loic-lopez,

Yes, of course, Zalenium can be deployed in a remote server and given that the network is configured properly, it can be reached without any issues. 

Moreover, this is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com) where the community can help you as well.

**Comment by loic-lopez** [comment]
@diemol thanks for reply but when il try to go on the live preview, it’s always display a timeout error.

**Comment by diemol** [comment]
@loic-lopez the thing is that with the information provided, it is not possible at all to know what is going on in your end. If you want to, please create a new issue **filling the whole template** and providing a way to reproduce the current status you have.
