### ISSUE TITLE
Enable basic auth makes zalenium return 401 at the second http request

### ISSUE THREAD

**Issue by megolee** [zalando/zalenium#824]
Zalenium Image Version(s):  
Latest

Docker Version:  
Docker version 18.09.0, build 4d60db4

OS: 
CentOS 7

Docker Command to start Zalenium:  
docker run --rm -d --name zalenium -p 80:4444 \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    -v /etc/resolv.conf:/etc/resolv.conf \
    -v /etc/resolv.conf:/tmp/node/etc/resolv.conf \
    --privileged dosel/zalenium start --timeZone "Asia/Shanghai" \
    --screenWidth 1024 --screenHeight 768 --gridUser "MyAccount" --gridPassword "MyPwd"

In my test script, I have set the server url like this "http://MyAccount:MyPwd@host/wd/hub", but http request return 401 after create session success. Please refer to below screenshot.

## Expected Behavior -
zalenium should works fine

## Actual Behavior -
Zalenium return 401 after session create success. The second http request does not take the auth info.
![request1](https://user-images.githubusercontent.com/9957802/50951120-0d9e7480-14e7-11e9-9749-ba4c02791df5.png)

![request2](https://user-images.githubusercontent.com/9957802/50951139-20b14480-14e7-11e9-9900-a33c0fd89325.png)

**Comment by diemol** [comment]
Well, you need to pass the auth token gotten after authenticating for the first time to the subsequent requests, otherwise how will the nginx sitting in front know that you have already authenticated?

This is what any http client in any programming language does, since you are doing things manually, you'll need to add the token in subsequent requests,
