### ISSUE TITLE
Keeps trying to start new node, test stuck

### ISSUE THREAD

**Issue by AronNovak** [zalando/zalenium#88]
![starting-new-node](https://cloud.githubusercontent.com/assets/114076/24363264/a1e4457e-130f-11e7-95aa-6771867cd119.png)

I started to use Zalenium instead of https://github.com/elgalu/docker-selenium, I changed my compose file (https://github.com/Gizra/drupal-elm-starter/pull/84/files) , but the test itself is not started, it seems Chrome never starts. How to approach this? Are there more verbose logging options or things like that?

**Comment by AronNovak** [comment]
On the test side, I send this:
![this](https://cloud.githubusercontent.com/assets/114076/24363385/017da750-1310-11e7-8388-5dd0eaa279ac.png)

**Comment by diemol** [comment]
Hi @AronNovak,

I think this behaviour gets produced by this [line](https://github.com/Gizra/drupal-elm-starter/pull/84/files#diff-29e631d8d8c3d5caab3b5e86ce4f6123R10).

When setting `--maxDockerSeleniumContainers 1`, then Zalenium will only create up to `1` `docker-selenium` containers at the same time. 

Since in your configuration you start already with `--firefoxContainers 1`, this Firefox container gets created, and no more are created until it gets used.

The purpose of `--maxDockerSeleniumContainers` it to limit the number of containers running, assuming that the host is being shared for other purposes. In your case, you could just increment this parameter to `10`, or a number that works for you.

I will also improve the logging there, because it is not possible to understand what is happening with the current output.

**Comment by AronNovak** [comment]
Your suggestion works perfectly, thanks, now indeed Zalenium acts as a drop-in replacement for us!
