### ISSUE TITLE
VNC Preview disconnecting

### ISSUE THREAD

**Issue by RameshEmis** [zalando/zalenium#891]
hi,
i am running Zalenium from AWS ec2 instance and i am unable to see preview in "http://ip/4444/grid/admin/live". VNC is disconnecting once immediately the url is loaded. i've connected in corporate network. Please help me to resolve this. 

Note: This is happening only when i connect through my corporate network and VNC is connecting through all other open networks.
![image](https://user-images.githubusercontent.com/42730758/53957398-441df780-4104-11e9-8bfa-c0cb62f8aec8.png)

Thanks

**Comment by diemol** [comment]
@RameshEmis 
Could you please help us to debug the issue? Can you please check the network tab in the developer console and look for errors?
It might be something related to the network where you are, which we can't really troubleshoot.

**Comment by RameshEmis** [comment]
Really i do not see any network error in console...!
![image](https://user-images.githubusercontent.com/42730758/53958661-a5939580-4107-11e9-8f1a-8fa9a9bca678.png)

![image](https://user-images.githubusercontent.com/42730758/53958684-b5ab7500-4107-11e9-89b9-cd90e0b12631.png)

Actually i am able to communicate to ec2 instance and run scripts through any network from my local machine but preview live is not connecting.

Thanks.

**Comment by diemol** [comment]
@RameshEmis it is hard to say where the connection gets lost. What Zalenium is simply doing is to connect to each container's noVNC client, and then proxing that live view through the LiveView servlet. 

You could manually connect to them by using the URLs configured under the hood, like:
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/5992658/54084127-1a93e480-432d-11e9-8389-33d03f0afd85.png">

and based on that, help us to diagnose the issue. On our side it is complicated since we don't have the same network configuration you have.

**Comment by RameshEmis** [comment]
It started working after we removed corporate proxy from LAN settings. Thanks for the support.
