### ISSUE TITLE
Whats the plan to upgrade the Chrome version from 72.X to latest in alignment to the official docker selenium project? 

### ISSUE THREAD

**Issue by sramgn** [zalando/zalenium#899]
Whats the plan to upgrade the Chrome version from 72.X to latest in alignment to the official docker selenium project?

**Comment by diemol** [comment]
I don't really understand what you mean by "in alignment", but anyway, both projects have already Chrome 73.

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by sramgn** [comment]
@diemol - Sorry if it was not clear. I was checking to see how do you guys fork or pull the latest changes from the mainstream selenium images into yours so this project is consistent and contains all the changes/core enhancements from the mainstream selenium project/images. For e.g, I still see that the Chrome image on Zalenium running on 72.X (that's what the dashboard reports) since I don't specify anything, but per your last comment you had mentioned that it's running Chrome 73.X. So what am I missing here?

**Comment by diemol** [comment]
Zalenium uses the elgalu/selenium images, not the official ones.
Just pull the latest from elgalu/selenium

**Comment by xparpx** [comment]
Today I update to Chrome 78 Version with this:

`docker pull elgalu/selenium:latest`

![image](https://user-images.githubusercontent.com/11421732/69869659-5e58c080-12a5-11ea-85f2-52d0aad5a05e.png)
