### ISSUE TITLE
Multiple cloud providers

### ISSUE THREAD

**Issue by degerlac** [zalando/zalenium#900]
Is it possible to have 2 cloud providers servicing requests in one zalenium system? One potential configuration would be to have one cloud provider handle mobile requests and another one to handle IE and other desktop browsers.

**Comment by diemol** [comment]
That should be in theory possible, give it a try and let us know how it went.

Closing since this is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
