### ISSUE TITLE
BrowserStack tests cannot test locally

### ISSUE THREAD

**Issue by nextlevelbeard** [zalando/zalenium#910]
## 🐛 Bug Report
The tests passed to BrowserStack cannot reach local domains because Local Testing is not activated.

The environment variable `BROWSER_STACK_TUNNEL_OPTS` has `--force-local` by default but tests have Local Testing set to false in BrowserStack, leaving them unable to reach the localhost and any white-listed domains on the host.

![browserstack local false](https://user-images.githubusercontent.com/3788982/55091675-902fdc80-50b1-11e9-95da-34a5a49acadd.png)

## To Reproduce

You'll need a BrowserStack account and set BROWSER_STACK_USER and BROWSER_STACK_KEY environment variables.

docker command:
```docker run --rm -ti --name zalenium -p 4444:4444 -e BROWSER_STACK_KEY -e BROWSER_STACK_USER -v /var/run/docker.sock:/var/run/docker.sock -v /c/Users/[USER]/videos:/home/seluser/videos --privileged dosel/zalenium start --videoRecordingEnabled true --browserStackEnabled true --startTunnel true```

Capabilities set (webdriverIO v5.7.6):
```
{
    browserName: 'safari',
},
```
I have tried to specify the capability to enable Local Testing which is `browserstack.local` according to the docs [here](https://www.browserstack.com/automate/webdriverio). 
I specified it like so:
```
{
    browserName: 'safari',
    "browserstack.local": true,
},
```
which prompted a WARN in Zalenium: `Cannot extract a capabilities from the request`
```
WARN  o.s.jetty9.server.HttpChannel - /wd/hub/session java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"capabilities":{"alwaysMatch":{"browserName":"safari","browserstack.local":true},"firstMatch":[{}]},"desiredCapabilities":{"browserName":"safari","browserstack.local":true}}
```
Without `browserstack.local` capability set, the tests run but Local Testing is set to false and tests do not reach the domain.

## Expected behavior

Local Testing should be set to true on BrowserStack and tests should be able to reach localhost and white-listed domains on the host.

## Environment

OS: Windows 10
Zalenium Image Version(s): 3.141.59i
Docker version: 18.09.0, build 4d60db4

**Comment by mansn** [comment]
@nextlevelbeard Since you closed the issue, does it mean that you solved it somehow? If so, how? 

I'm currently experiencing a HTTP 500 from Zalenium when I POST to `/wd/hub` with the following payload:

```
{
	"capabilities": {
		"alwaysMatch": {
			"browserstack.local": true,
			"browserName": "safari"
		},
		"firstMatch": [{}]
	},
	"desiredCapabilities": {
		"browserstack.local": true,
		"browserName": "safari"
	}
}
```
The response body contains this error:
```
...
<p>Problem accessing /wd/hub/session. Reason:
		<pre>    Server Error</pre>
	</p>
	<h3>Caused by:</h3>
	<pre>java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request:
.... 
```

Zalenium running Selenium GRID with v.3.141.59, connected with Browserstack.

Note: If I remove `"browserstack.local": true,`, then it works without any problems.

**Comment by nextlevelbeard** [comment]
@mansn you are using the outdated way of specifying the capabilities
Set your capabilities up with the helper BrowserStack provides here: https://www.browserstack.com/automate/capabilities?tag=selenium-4

Make sure to use the W3C protocol.
Your example:
```js
{
    browserName: 'safari',
    "browserstack.local": true,
},
```
becomes 
```js
{
    browserName: 'safari',
    "bstack:options": {
        local: true
    }
},
```

**Comment by mansn** [comment]
@nextlevelbeard Thanks for the quick reply! Interesting. I've been looking into this a bit as well (i.e. capabilities being outdated).. but still without progress.

I tried the updated capabilities you sent, as well as including the `localIdentifier: 'zalenium'` inside `bstack:options`, and now I got another error:
**ERROR webdriver: Request failed due to Error: The property '#/firstMatch/0/bstack:options/osVersion' of type Fixnum did not match the following type: string in the payload.**

I'm not exactly sure where this type checking takes place. AFAIK I don't have any control over "firstMatch" via WebdriverIO.

Do these capabilities also apply if we're running Zalenium with Selenium GRID with v.3.141.59? 
On the Grid Hub Console we've got a BrowserStackRemoteProxy on version : 2.45.0.

I'm using WebdriverIO 5.12.5, not sure about the exact **Zalenium version** though.. but I hope the versions above should be enough info =). Are you getting this to work with the versions you posted above, with WebdriverIO?

### Details (here you'll see the capabilities being sent)
```
2019-09-05T08:14:13.866Z INFO webdriver: [POST] http://zalenium.supersecretdomain.com:80/wd/hub/session
[0-0] 2019-09-05T08:14:13.866Z INFO webdriver: DATA {
  capabilities: {
    alwaysMatch: {
      browserName: 'Safari',
      'appium:deviceName': 'iPhone 8 Plus',
      'bstack:options': [Object]
    },
    firstMatch: [ {} ]
  },
  desiredCapabilities: {
    browserName: 'Safari',
    'appium:deviceName': 'iPhone 8 Plus',
    'bstack:options': {
      deviceName: 'iPhone 8 Plus',
      realMobile: true,
      osVersion: 11,
      local: true,
      localIdentifier: 'zalenium'
    }
  }
}
[0-0] 2019-09-05T08:14:14.478Z ERROR webdriver: Request failed due to Error: The property '#/firstMatch/0/bstack:options/osVersion' of type Fixnum did not match the following type: string in the payload.
    at getErrorFromResponseBody (/Users/snip/gitworkspace/automation-test/node_modules/webdriver/build/utils.js:215:10)
    at Request._callback (/Users/snip/gitworkspace/automation-test/node_modules/webdriver/build/request.js:103:64)
    at Request.self.callback (/Users/snip/gitworkspace/automation-test/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/Users/snip/gitworkspace/automation-test/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:203:13)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/Users/snip/gitworkspace/automation-test/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:291:20)
```

**Comment by nextlevelbeard** [comment]
@mansn I made a mistake, `osVersion` needs to be a `string`, not a Number. So, `"11"`, not `11`. 
The error is pretty clear about this:
`The property '#/firstMatch/0/bstack:options/osVersion' of type Fixnum did not match the following type: string `

**Comment by mansn** [comment]
@nextlevelbeard Ah thanks, I should probably have realized that. I thought I tried `"11"`, but apparently not. I tried it now and it works fine =).

Thanks a lot for your time! I really appreciate it!

Ps. The xpath in the error looks weird to me... looks like it's referring to the first index in the `firstMatch` array.. but that's empty.. I'm not an xPath expert though. Ds.
