### ISSUE TITLE
zalenium Containers docker-compose Configuration Parameters

### ISSUE THREAD

**Issue by Pratish-minted** [zalando/zalenium#913]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)

What is the purpose difference 
`maxDockerSeleniumContainers`
`desiredContainers`
`maxTestSessions`

**Comment by diemol** [comment]
@Pratish-minted 
There is a table explaining all these parameters https://opensource.zalando.com/zalenium/#docker

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by Pratish-minted** [comment]
thank you! @diemol
