### ISSUE TITLE
As the Videos are displayed in Dashboard, my question is: are these videos stored in Zalenium docker image that we pulled ? or they are stored in local system? If they are stored in local system then how can we access them through file structure/ windows explorer? 

### ISSUE THREAD

**Issue by nisargdave1993** [zalando/zalenium#919]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
@nisargdave1993 if you started Zalenium with the example commands from the docs, they will be in the directory you mapped for videos.

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
