### ISSUE TITLE
Internet Explorer browser is not supported: Only Chrome & Firefox browsers supported. Can we consider IE as well for execution?

### ISSUE THREAD

**Issue by nisargdave1993** [zalando/zalenium#922]
### Please note that this issue tracker is not a help form and this issue will be closed.

For questions or help please see:

- [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium)
- [Slack channel - #zalenium channel](https://seleniumhq.herokuapp.com/)

**Comment by diemol** [comment]
@nisargdave1993 There is no standard way provided from Microsoft to do that, there are workarounds that involve having Linux machines with virtualization, QEMU and Libvirt. 

This is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
