### ISSUE TITLE
nodes are registered twice (once with the ip, once with localhost)

### ISSUE THREAD

**Issue by ilyache** [zalando/zalenium#95]
Hey guys, 

I've used the command from the documentation to boot up the grid, and I saw that nodes are being registered both under `localhost` and both under `172.17.0.2`. Check out the screenshot:
![image](https://cloud.githubusercontent.com/assets/14318385/24944166/a1b972f4-1f62-11e7-8b88-b1061b5fbd80.png)

Is this the expected behavior? I'd like to have each node only registered ones, this seems confusing.

**Comment by ilyache** [comment]
Seems like that "ghost" node that's registered under the IP is just for tests to not get declined when they first reach the hub, otherwise there will be node that fits their desired caps. Can anyone confirm? Or if that's incorrect, explain why it's there? 

Thanks!

**Comment by diemol** [comment]
Hi @ilyache,

That is the expected behaviour. 
The node registered on `172.17.0.2` is the `DockerSeleniumStarterProxy`. This is the one in charge of creating more nodes/containers on the fly. It is vital for Zalenium to work properly. The rest of the nodes are `DockerSeleniumProxy` nodes.

To be honest, I don't know why it uses an IP instead of `localhost` (this has to do with the internal grid methods).

**Comment by ilyache** [comment]
Gothca, thanks @diemol!
