### ISSUE TITLE
[Dashboard] Cleanup feature

### ISSUE THREAD

**Issue by beniamin-kis** [zalando/zalenium#99]
Because usually we try to keep our CI environments as clean as we can, it would be nice to have a **cleanup feature** for the dashboard, in case Zalenium is set up to keep running, as a selenium grid for testing on multiple applications (thus multiple Jenkins jobs running on the same hub).
At first I'm thinking of a simple button to remove all entries, then this could be implemented with custom settings, like:
- auto-remove entries which are older than x no of days/weeks/months.
- only remove logs, keep the videos
- only remove videos, keep the logs
etc. you-name-it

**Comment by robertzett** [comment]
@beniamin-kis if I understood your main concern right, then your are looking for a way to save disk space in your CI. In this case I would suggest to remove entries by simply deleting them in your videos folder (`/tmp/videos` if you use the defaults when starting docker).
For removing all entries this could be something like this (should work for macOS and linux):
```
find /tmp/videos -mindepth 1 -maxdepth 1 \
! -name css ! -name js ! -name index.html \
-exec rm -rf {} \;
```
You could place this in an cleanup job in your CI an run it at a schedule of your choice.

Removing entries older than an amount of time would be similar easy by adding an option to the above find command. Example for one day:
```
find /tmp/videos -mindepth 1 -maxdepth 1 \
! -name css ! -name js ! -name index.html \
-mtime +1d \
-exec rm -rf {} \;
```

The above find commands could also be placed inside a script which would be provided by zalenium in one of the next releases so that you only have to call such a script inside the videos folder from your CI.
The dashboard creating functionality in zalenium would need to be enhanced to handle those file removal correctly also. The dashboard currently would count the number of tests incorrectly and in case of removing only some files it would still list the no longer existing entries.

What do you think about this @beniamin-kis would that already help you?

**Comment by beniamin-kis** [comment]
yeah, as a temporary solution this is what I do:
`docker ps -a | grep zalenium | awk '{print $1}' | xargs docker rm -f &&
sudo rm -rf /tmp/videos || exit 0`

I've set up a cleanup job in Jenkins which runs the script above, then reinitializes Zalenium.

Tho, it would have been a neat feature to do it from the dashboard. :)

**Comment by robertzett** [comment]
I've been working on an initial show case for such a  "simple button to remove all entries" on the history page.
The implementation is on a branch in my repo:
https://github.com/robertzett/zalenium/tree/cleanup-feature
What do you think?

**Comment by diemol** [comment]
Hi @robertzett,

Thanks for this! We will review the PR in the next 2-3 days, so far it looks good 😄

**Comment by diemol** [comment]
I merged the feature from @robertzett to master, we will release it next Monday.

@robertzett sadly the contribution is not shown in the commits because it seems there is an issue with your git configuration, see:

![image](https://cloud.githubusercontent.com/assets/5992658/26213566/dd2c60ae-3bf9-11e7-8956-f77ea42fe31c.png)

**Comment by diemol** [comment]
This was released in https://github.com/zalando/zalenium/releases/tag/3.3.1f, we need to improve the UI but the feature is there. It can also be accessed directly via `http://localhost:5555/cleanup?action=doCleanupAll`

**Comment by robertzett** [comment]
Thanks @diemol for the information on the configuration issue. I've not been aware of the importance of the option "Keep my email address private".
