### ISSUE TITLE
Alternative Docker Swarm Exec

### ISSUE THREAD

**Issue by tstern** [zalando/zalenium#991]
## Alternative Docker Swarm Exec

Zalenium executes following commands on browser containers after a test has been finished:

1. `[task-exec, 4tl6qb78zswjagszzx7frylpy, notify 'Zalenium', 'TEST COMPLETED', --icon=/home/seluser/images/completed.png]`
2. `[task-exec, 4tl6qb78zswjagszzx7frylpy, transfer-logs.sh]`
3. `[task-exec, 4tl6qb78zswjagszzx7frylpy, cleanup-container.sh]`

Code: [zalenium/container/ContainerClient.java#L17](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/ContainerClient.java#L17) 

Docker swarm doesn't provide a native solution to execute commands on containers on different docker nodes. For the docker swarm implementation we use https://github.com/opsani/skopos-plugin-swarm-exec to execute the commands above.

So I have the following two questions:

- Does someone know another easy solution to provide browser container execution without the need of creating new containers?
- Can someone please explain what the commands listed above actually do and how they are involved in the testing execution process?

Also I wasn't able to find the script `transfer-logs.sh` in https://github.com/elgalu/docker-selenium/tree/master/bin 

## Motivation

Find an easy and secure solution to execute commands on browser containers on different docker nodes.

## Example

An implementation like [DockerContainerClient.java#L238](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/DockerContainerClient.java#L238)  for [SwarmContainerClient.java#L141](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/container/swarm/SwarmContainerClient.java#L141).

**Comment by diemol** [comment]
Hi @tstern 

>Does someone know another easy solution to provide browser container execution without the need of creating new containers?

Not really, perhaps we could implement Servlets for the nodes and execute those commands via REST calls. The thing is that the Grid is being rewritten for Selenium 4 and perhaps we would need to rewrite them soon. Another option would be to have a REST server in the browser container to receive REST calls and execute those commands.

>Can someone please explain what the commands listed above actually do and how they are involved in the testing execution process?

- The first one displays a pop up when the test completes.
- Second one can be removed, I think we removed it from the browser container and we forgot to remove the call from Zalenium -> https://github.com/elgalu/docker-selenium/blob/master/CHANGELOG.md#331-p9
- Third one resets the container when it is being used for more than one test (deletes local logs and video files).

I would suggest to keep this open and retake it when we find a migration path for Selenium 4 (which is not clear since Grid 4.0 is not ready yet).

**Comment by diemol** [comment]
Just an update here, due to the changes that Grid 4.x will have, it becomes really hard to migrate Zalenium to use it. It will be easier to write it from scratch. 
Therefore, I have decided to work in the upstream docker-selenium project and port as much functionalities from Zalenium to it. If anyone wants to give us a hand, just start checking the open issues in the Selenium project.
Additionally, I will be around the Zalenium project in case anyone wants to help with it, I will contribute by reviewing and merging PRs, but won't be around to implement new functionalities.

Therefore, I will close this issue. Thanks!
