### ISSUE TITLE
How to upload the test result to AWS s3

### ISSUE THREAD

**Issue by megolee** [zalando/zalenium#992]
## 💬 Questions and Help

Is there a detail doc about how to upload to test result like videos, html files to the aws s3 storage?

I have read the doc about `Send video and logs to some external system for storage`, but still have no idea how to do it.

Thanks.

**Comment by diemol** [comment]
@megolee 
That feature demands an implementation on your side where you could wrap the AWS client to store the videos and logs. In addition, you could also implement a cron job that copies files to S3.

Moreover, this is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.
