### ISSUE TITLE
CBT with Zalenium windows

### ISSUE THREAD

**Issue by hanabizhani** [zalando/zalenium#994]
Hi,

I want to have Cross browser Testing with docker-selenium and zalenium.

The AUT is a web application with too many users running different firefox versions on different windows OS.

The question is, how can I create an CBT environment which meets this requirement. As elgalu/selenium and dosel/zalenium are linux base, I should set the platform in the test suite as linux and this runs last version of firefox on linux which is not what I want.

I'll appreciate if you help me. I really mixed up.

Thanks alot,
Hana

**Comment by diemol** [comment]
@hanabizhani so far it is only possible to run in a lightweight way Chrome and Firefox in Docker containers based on the Linux operating system.
For any other platform, you would need to setup your own VMs or real machines.

Moreover, this is a question rather than an issue. Please ask questions in the #zalenium channel at [Slack](https://goo.gl/9o4J3Y)  or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Comment by hanabizhani** [comment]
Thanks for your answer, and sorry if I asked my question in the wrong place
